import { useTranslation } from "react-i18next";

type Language = "zh-CN" | "en";

const labels: Record<Language, Record<string, string>> = {
  "zh-CN": {
    single_signal_identity: "单信号直通",
    flat_equal_weight_mean: "信号等权平均",
    hierarchical_weighted_mean: "分层加权平均",
    directional_weighted_vote: "方向加权投票",
    ols_cross_sectional_regression: "OLS 横截面线性回归",
    ridge_cross_sectional_regression: "Ridge 横截面回归",
    random_forest_cross_sectional_regression: "随机森林横截面回归",
    lightgbm_cross_sectional_regression: "LightGBM 横截面回归",
    xgboost_cross_sectional_regression: "XGBoost 横截面回归",
    forward_rank_h5: "未来 5 个交易日横截面排名",
    forward_rank_h10: "未来 10 个交易日横截面排名",
    forward_rank_h21: "未来 21 个交易日横截面排名",
    expanding_daily_ols_v1: "扩展窗口日频 OLS",
    expanding_daily_ridge_alpha1_v1: "扩展窗口日频 Ridge（α=1）",
    expanding_daily_rf_balanced_v1: "随机森林稳健基线",
    expanding_daily_rf_feature_subsample_v1: "随机森林特征采样",
    expanding_daily_lightgbm_balanced_v1: "LightGBM 稳健基线",
    expanding_daily_lightgbm_feature_subsample_v1: "LightGBM 特征采样",
    expanding_daily_xgb_balanced_v1: "XGBoost 稳健基线",
    expanding_daily_xgb_feature_subsample_v1: "XGBoost 特征采样",
    cross_section_rank_top_k_parity: "ETF 横截面 Top-K",
    cross_section_rank_top_k_large_cap_parity: "大盘股横截面 Top-K",
    fixed20_defense: "固定 20% 防御",
    ma200_defense: "标普 500 均线防御",
    ma200_tiered_defense: "标普 500 二百日均线分档防御",
    spy_ma200_tiered_budget: "标普 500 二百日均线分档预算",
    fixed20_budget: "固定防御预算",
    standard_defensive_basket_long_history_v1: "标准长历史防御篮子",
    none: "不启用防御",
    signal_equal_v1: "信号等权",
    legacy_dimension_equal_v1: "旧版维度等权",
    legacy_trend_tilt_v1: "旧版趋势倾斜",
    legacy_defensive_tilt_v1: "旧版防御倾斜",
    active_dimension_equal_component_equal_v1: "原生维度与维度内信号双层等权",
    momentum_trend: "动量与趋势",
    tail_shape: "收益分布形态",
    technical_event: "技术事件",
    technical_state: "技术状态",
    relative_strength: "相对强弱",
    k1: "持有排名第 1 的资产",
    k2: "持有排名前 2 的资产",
    k3: "持有排名前 3 的资产",
    k10: "持有排名前 10 的资产",
    k20: "持有排名前 20 的资产",
    descending: "降序排名",
    explicit_input_order: "按用户明确选择的输入顺序",
    fail: "缺失即停止，不静默填补",
    stable_input_order: "按稳定输入顺序处理并列",
    long_only: "仅做多",
    with_strategy: "随策略一起调仓",
    forbidden: "禁止静默回退",
    reserve: "现金储备",
    synthetic_reserve: "合成现金储备",
    ief: "美国 7–10 年期国债 ETF（IEF）",
    tlt: "美国 20 年以上国债 ETF（TLT）",
    tip: "美国通胀保值债券 ETF（TIP）",
    iau: "黄金 ETF（IAU）",
    open_raw: "原始开盘价",
    high_raw: "原始最高价",
    low_raw: "原始最低价",
    close_raw: "原始收盘价",
    adjusted_close: "总收益复权收盘价",
    volume_raw: "原始成交量",
    cash_dividend: "现金分红",
    split_ratio: "拆股比例",
    dgs3mo_rate: "三个月期美债利率",
    amihud_illiquidity: "Amihud 非流动性",
    daily_price_impact: "Amihud 单日非流动性原始值",
    death_cross_event: "死亡交叉事件",
    deep_drawdown_reversal: "深度回撤反转",
    dollar_volume: "成交额",
    dollar_volume_attention: "成交额关注度",
    downside_deviation: "下行波动率",
    lagged_return: "跳过近期的历史收益",
    lagged_return_continuation: "滞后收益延续",
    golden_cross_event: "黄金交叉事件",
    high_kurtosis_tail_regime: "高峰度尾部状态",
    high_skew_regime: "高偏度状态",
    illiquidity_premium: "非流动性溢价",
    low_downside_risk: "低下行风险",
    low_illiquidity_quality: "高流动性质量",
    low_kurtosis_quality: "低峰度质量",
    low_skew_premium: "低偏度溢价",
    low_volatility: "低波动率",
    ma_trend_strength: "均线趋势强度",
    maximum_drawdown: "区间最大回撤",
    moving_average_ratio: "移动平均线比率",
    ppo_histogram: "PPO 柱状差",
    ppo_cross_above_zero: "PPO 上穿零轴",
    ppo_cross_below_zero: "PPO 下穿零轴",
    ppo_trend_acceleration: "PPO 趋势加速度",
    price_above_ma_state: "价格位于均线上方",
    price_cross_above_ma: "价格上穿均线",
    price_cross_below_ma: "价格下穿均线",
    realized_volatility: "已实现波动率",
    relative_dollar_volume: "相对成交额",
    return_excess_kurtosis: "收益超额峰度",
    return_skewness: "收益偏度",
    rsi: "相对强弱指标（RSI）",
    rsi_mean_reversion: "RSI 均值回归",
    rsi_overbought_state: "RSI 超买状态",
    rsi_oversold_state: "RSI 超卖状态",
    rsi_relative_strength: "RSI 相对强势",
    short_return_reversal: "短期收益反转",
    simple_return: "单期简单收益",
    return_continuation: "收益延续",
    drawdown_resilience: "回撤韧性",
    total_return: "区间总收益",
    liquidity: "成交量与流动性",
    oscillator: "反转与超买超卖",
    return: "动量与收益",
    risk: "波动与风险",
    tail_distribution: "尾部分布",
    trend: "趋势",
    weekly: "周频",
    monthly: "月频",
    canonical: "经典参数",
    horizon_anchor: "期限锚点",
    sensitivity: "敏感性参数",
    exploratory: "探索参数",
    positive: "正向",
    negative: "反向",
    continuous: "连续分数",
    directional: "方向信号",
    selected_by_rank: "按模型排名入选",
    excluded_by_rank: "未进入目标排名",
    blocked_by_trend: "趋势过滤未通过",
    positive_trend: "趋势为正",
    negative_trend: "趋势为负",
    no_trend_filter: "未启用趋势过滤",
    weighted_sum: "加权求和",
    weighted_mean: "加权平均",
    directional_vote: "方向投票",
    equal_weight: "等权聚合",
    spy_buy_and_hold: "SPY 买入并持有",
    full_history: "全历史区间",
    accepted: "已接受",
    capacity_rejected: "容量拒绝",
    failed: "失败",
    pending: "待运行",
    running: "运行中",
    defined: "已定义",
    completed: "已完成",
    passed: "通过",
    selected: "已入选",
    below_cutoff: "低于入选边界",
    very_short_sample_warning: "样本极短，结果仅供流程验证",
    strategy: "策略",
    benchmark: "基准",
    relative: "相对基准",
    cumulative_return: "累计收益",
    cagr: "年化复合收益（CAGR）",
    annualized_volatility: "年化波动率",
    sharpe_ratio: "Sharpe 比率",
    sortino_ratio: "Sortino 比率",
    maximum_drawdown_duration_days: "最大回撤持续天数",
    calmar_ratio: "Calmar 比率",
    positive_daily_return_ratio: "日收益为正比例",
    best_daily_return: "最佳单日收益",
    worst_daily_return: "最差单日收益",
    positive_monthly_return_ratio: "月收益为正比例",
    best_monthly_return: "最佳单月收益",
    worst_monthly_return: "最差单月收益",
    cumulative_relative_return: "累计相对收益",
    annualized_relative_wealth_growth: "相对财富年化增长",
    cagr_spread: "CAGR 差值",
    tracking_error: "跟踪误差",
    information_ratio: "信息比率",
    return_correlation: "收益相关性",
    beta: "Beta",
    annualized_alpha: "年化 Alpha",
    accepted_result_inputs: "正式结果输入已固定",
    all_outputs_published: "全部输出已发布",
    interval_availability: "实验区间可用",
    run_started: "实验运行开始",
    artifact_published: "发布物已生成",
    quality_checks_completed: "质量检查完成",
    run_completed: "实验运行完成",
    trailing_10_years: "最近 10 年",
    trailing_5_years: "最近 5 年",
    trailing_3_years: "最近 3 年",
    trailing_1_year: "最近 1 年",
    short_sample_warning: "短样本提醒",
    weekly_next_open_to_next_open: "下周开盘至再下周开盘收益",
    monthly_next_open_to_next_open: "下月开盘至再下月开盘收益",
    higher_is_better: "数值越高，信号越强",
    lower_is_better: "数值越低，信号越强",
    attention_liquidity: "关注度与流动性",
    downside_risk: "下行风险",
    drawdown_risk: "回撤风险",
    liquidity_premium: "流动性溢价",
    liquidity_quality: "流动性质量",
    low_risk: "低风险",
    momentum: "动量",
    reversal: "反转",
    tail_premium: "尾部溢价",
    tail_regime: "尾部状态",
    tail_risk: "尾部风险",
    parity: "对齐研究",
    ranking: "排名方向",
    selection: "选择方式",
    tie_break: "并列处理",
    allowed_k: "可选持仓数量",
    frequencies: "支持频率",
    decision_cutoff: "决策截点",
    weighting: "权重方式",
    missing_decision: "缺失处理",
    risk_sleeve: "风险资产预算",
    defense_sleeve: "防御资产预算",
    rebalance_with_strategy: "随策略调仓",
    market_timing_signal_required: "需要择时信号",
    known_at_required: "要求可用时间",
    missing_input: "缺失输入处理",
    missing_input_policy: "缺失输入处理",
    indicator: "市场状态指标",
    indicator_key: "指标键",
    above_upper_budget: "强势区间防御预算",
    middle_budget: "中性区间防御预算",
    below_lower_budget: "弱势区间防御预算",
    moving_average_tiered_budget: "移动平均线分档预算",
    reference_asset_key: "参考资产",
    price_field: "价格字段",
    moving_average_window_sessions: "移动平均窗口（交易日）",
    upper_threshold: "上阈值",
    lower_threshold: "下阈值",
    risk_budget: "风险资产预算",
    defense_budget: "防御资产预算",
    boundary_policy: "边界规则",
    strict_outer_inclusive_middle: "外侧严格、中间区间含边界",
    spy_close_div_sma200_minus_one: "标普 500 收盘价 ÷ 200 日均线 − 1",
    spy: "标普 500（SPY）",
    target_k: "目标持仓数",
    sector_cap: "行业上限",
    selection_buffer: "入选缓冲",
    rule_type: "规则类型",
    fixed_budget: "固定预算",
    top_k: "选取前 K 名",
    asset_key: "按资产代码",
    equal_selected_assets: "入选资产等权",
    after_completed_session: "交易时段结束后",
    yes: "是",
    no: "否",
  },
  en: {
    single_signal_identity: "Single-signal pass-through",
    flat_equal_weight_mean: "Equal-weight signal mean",
    hierarchical_weighted_mean: "Hierarchical weighted mean",
    directional_weighted_vote: "Directional weighted vote",
    ols_cross_sectional_regression: "OLS cross-sectional regression",
    ridge_cross_sectional_regression: "Ridge cross-sectional regression",
    random_forest_cross_sectional_regression: "Random-forest cross-sectional regression",
    lightgbm_cross_sectional_regression: "LightGBM cross-sectional regression",
    xgboost_cross_sectional_regression: "XGBoost cross-sectional regression",
    forward_rank_h5: "Forward 5-session cross-sectional rank",
    forward_rank_h10: "Forward 10-session cross-sectional rank",
    forward_rank_h21: "Forward 21-session cross-sectional rank",
    expanding_daily_ols_v1: "Expanding daily OLS",
    expanding_daily_ridge_alpha1_v1: "Expanding daily Ridge (alpha 1)",
    expanding_daily_rf_balanced_v1: "Random forest balanced baseline",
    expanding_daily_rf_feature_subsample_v1: "Random forest feature subsampling",
    expanding_daily_lightgbm_balanced_v1: "LightGBM balanced baseline",
    expanding_daily_lightgbm_feature_subsample_v1: "LightGBM feature subsampling",
    expanding_daily_xgb_balanced_v1: "XGBoost balanced baseline",
    expanding_daily_xgb_feature_subsample_v1: "XGBoost feature subsampling",
    cross_section_rank_top_k_parity: "ETF cross-sectional Top-K",
    cross_section_rank_top_k_large_cap_parity: "Large-cap cross-sectional Top-K",
    fixed20_defense: "Fixed 20% defense",
    ma200_defense: "S&P 500 moving-average defense",
    ma200_tiered_defense: "S&P 500 200-day moving-average tiered defense",
    spy_ma200_tiered_budget: "S&P 500 200-day moving-average tiered budget",
    fixed20_budget: "Fixed defensive budget",
    standard_defensive_basket_long_history_v1: "Standard long-history defensive basket",
    none: "No defense",
    signal_equal_v1: "Signal equal weight",
    legacy_dimension_equal_v1: "Legacy dimension equal weight",
    active_dimension_equal_component_equal_v1: "Native equal dimensions and components",
    tail_shape: "Return distribution shape",
    technical_event: "Technical events",
    technical_state: "Technical states",
    relative_strength: "Relative strength",
    legacy_trend_tilt_v1: "Legacy trend tilt",
    legacy_defensive_tilt_v1: "Legacy defensive tilt",
    k1: "Hold the top-ranked asset",
    k2: "Hold the top 2 assets",
    k3: "Hold the top 3 assets",
    k10: "Hold the top 10 assets",
    k20: "Hold the top 20 assets",
    descending: "Descending rank",
    explicit_input_order: "Explicit user-selected input order",
    fail: "Fail on missing data",
    stable_input_order: "Stable input-order tie break",
    long_only: "Long only",
    with_strategy: "Rebalance with strategy",
    forbidden: "No silent fallback",
    reserve: "Cash reserve",
    synthetic_reserve: "Synthetic cash reserve",
    ief: "7–10 Year Treasury ETF (IEF)",
    tlt: "20+ Year Treasury ETF (TLT)",
    tip: "Inflation-Protected Treasury ETF (TIP)",
    iau: "Gold ETF (IAU)",
    amihud_illiquidity: "Amihud illiquidity",
    downside_deviation: "Downside deviation",
    lagged_return: "Skip-period return",
    maximum_drawdown: "Window maximum drawdown",
    moving_average_ratio: "Moving-average ratio",
    ppo_histogram: "PPO histogram",
    realized_volatility: "Realized volatility",
    relative_dollar_volume: "Relative dollar volume",
    return_excess_kurtosis: "Return excess kurtosis",
    return_skewness: "Return skewness",
    rsi: "Relative Strength Index (RSI)",
    total_return: "Total return",
    liquidity: "Volume and liquidity",
    oscillator: "Reversal and oscillator",
    return: "Momentum and return",
    risk: "Volatility and risk",
    tail_distribution: "Tail distribution",
    trend: "Trend",
    canonical: "Canonical preset",
    horizon_anchor: "Horizon anchor",
    sensitivity: "Sensitivity preset",
    exploratory: "Exploratory preset",
    positive: "Positive",
    negative: "Negative",
    continuous: "Continuous score",
    directional: "Directional signal",
    selected_by_rank: "Selected by model rank",
    excluded_by_rank: "Outside target rank",
    blocked_by_trend: "Blocked by trend filter",
    positive_trend: "Positive trend",
    negative_trend: "Negative trend",
    no_trend_filter: "No trend filter",
    weighted_sum: "Weighted sum",
    weighted_mean: "Weighted mean",
    directional_vote: "Directional vote",
    equal_weight: "Equal-weight aggregation",
    spy_buy_and_hold: "SPY buy and hold",
    full_history: "Full history",
    accepted: "Accepted",
    capacity_rejected: "Capacity rejected",
    failed: "Failed",
    pending: "Pending",
    running: "Running",
    defined: "Defined",
    completed: "Completed",
    passed: "Passed",
    selected: "Selected",
    below_cutoff: "Below selection cutoff",
    very_short_sample_warning: "Very short sample; workflow validation only",
    strategy: "Strategy",
    benchmark: "Benchmark",
    relative: "Relative",
    cumulative_return: "Cumulative return",
    cagr: "Compound annual growth rate (CAGR)",
    annualized_volatility: "Annualized volatility",
    sharpe_ratio: "Sharpe ratio",
    sortino_ratio: "Sortino ratio",
    maximum_drawdown_duration_days: "Maximum drawdown duration (days)",
    calmar_ratio: "Calmar ratio",
    positive_daily_return_ratio: "Positive daily return ratio",
    best_daily_return: "Best daily return",
    worst_daily_return: "Worst daily return",
    positive_monthly_return_ratio: "Positive monthly return ratio",
    best_monthly_return: "Best monthly return",
    worst_monthly_return: "Worst monthly return",
    cumulative_relative_return: "Cumulative relative return",
    annualized_relative_wealth_growth: "Annualized relative wealth growth",
    cagr_spread: "CAGR spread",
    tracking_error: "Tracking error",
    information_ratio: "Information ratio",
    return_correlation: "Return correlation",
    beta: "Beta",
    annualized_alpha: "Annualized alpha",
    accepted_result_inputs: "Accepted-result inputs",
    all_outputs_published: "All outputs published",
    interval_availability: "Interval availability",
    run_started: "Experiment run started",
    artifact_published: "Artifact published",
    quality_checks_completed: "Quality checks completed",
    run_completed: "Experiment run completed",
    trailing_10_years: "Trailing 10 years",
    trailing_5_years: "Trailing 5 years",
    trailing_3_years: "Trailing 3 years",
    trailing_1_year: "Trailing 1 year",
    short_sample_warning: "Short-sample warning",
    weekly_next_open_to_next_open: "Next weekly open-to-open return",
    monthly_next_open_to_next_open: "Next monthly open-to-open return",
    higher_is_better: "Higher values rank better",
    lower_is_better: "Lower values rank better",
    attention_liquidity: "Attention and liquidity",
    downside_risk: "Downside risk",
    drawdown_risk: "Drawdown risk",
    liquidity_premium: "Liquidity premium",
    liquidity_quality: "Liquidity quality",
    low_risk: "Low risk",
    momentum: "Momentum",
    reversal: "Reversal",
    tail_premium: "Tail premium",
    tail_regime: "Tail regime",
    tail_risk: "Tail risk",
  },
};

const formulaGuides: Record<string, { notation: string; zh: string; en: string }> = {
  ols_cross_sectional_regression: { notation: "β̂ = argminβ ‖y − Xβ‖²", zh: "用全部已选信号解释未来横截面收益排名；系数只使用当时已成熟的历史标签，在严格样本外窗口生成预测。", en: "Fits all selected signals to forward cross-sectional return ranks using matured labels only, then emits strict out-of-sample predictions." },
  ridge_cross_sectional_regression: { notation: "β̂ = argminβ (‖y − Xβ‖² + α‖β‖²)", zh: "在线性回归上加入 L2 收缩，降低高度相关信号造成的系数不稳定；α 与训练窗口均作为冻结方案保存。", en: "Adds L2 shrinkage to stabilize coefficients when signals are correlated; alpha and the walk-forward recipe are frozen." },
  random_forest_cross_sectional_regression: { notation: "ŷ = B⁻¹ Σᵦ Tᵦ(X)", zh: "对多棵回归树的样本外预测取平均，可表达非线性和信号交互；树深、特征采样与随机种子均被冻结。", en: "Averages out-of-sample predictions from regression trees to capture nonlinearities and interactions; depth, feature sampling, and seed are frozen." },
  lightgbm_cross_sectional_regression: { notation: "ŷ = Σₘ η fₘ(X)", zh: "逐轮拟合残差的梯度提升树，输出未来横截面排名分数；只使用严格走步训练中当时已成熟的标签。", en: "Gradient-boosted trees fit residual structure and predict forward cross-sectional ranks using only labels matured at each walk-forward cutoff." },
  xgboost_cross_sectional_regression: { notation: "ŷ = Σₘ η fₘ(X),  Ω(fₘ)", zh: "带显式正则项的梯度提升树，用于学习非线性横截面关系；深度、采样、正则化与线程设置均进入冻结身份。", en: "Regularized gradient-boosted trees learn nonlinear cross-sectional relationships; depth, sampling, regularization, and threading enter the frozen identity." },
  spy_ma200_tiered_budget: { notation: "dₜ = SPYₜ ÷ SMA₂₀₀,t − 1", zh: "用标普 500 复权收盘价相对 200 日均线的位置判断市场状态：高于 +2% 不配置防御，中间区间配置 20%，低于 −2% 配置 40%。", en: "Uses the S&P 500 adjusted close relative to its 200-session average: no defense above +2%, 20% defense in the middle tier, and 40% defense below −2%." },
  standard_defensive_basket_long_history_v1: { notation: "40% 现金储备 + 25% IEF + 10% TLT + 15% TIP + 10% IAU", zh: "防御袖套内部采用冻结的长历史配置；最终组合权重还会乘以当期防御预算。", en: "Frozen long-history weights inside the defensive sleeve; final portfolio weights are scaled by the current defensive budget." },
  daily_price_impact: { notation: "|rₜ| ÷ (Pₜ × Vₜ)", zh: "Amihud 非流动性指标的单日原始值：单位成交额对应的绝对价格变动越大，流动性通常越差。", en: "Daily Amihud input: absolute return per unit of dollar volume; larger values generally indicate worse liquidity." },
  dollar_volume: { notation: "Pₜ × Vₜ", zh: "收盘价与成交量的乘积，近似当日成交金额。", en: "Closing price times volume, an approximation of daily traded value." },
  simple_return: { notation: "Pₜ ÷ Pₜ₋₁ − 1", zh: "相邻两个交易日之间的简单收益率。", en: "Simple return between consecutive trading sessions." },
  amihud_illiquidity: { notation: "mean(|rₜ| ÷ (Pₜ × Vₜ), w)", zh: "窗口内，单位成交额对应的绝对收益变动；数值越高通常表示越不易交易。", en: "Mean absolute return per unit of dollar volume; higher values generally indicate lower liquidity." },
  downside_deviation: { notation: "√(252 × mean(min(rₜ, 0)², w))", zh: "只保留负收益并年化，衡量投资者更关心的下行波动。", en: "Annualized volatility using negative returns only, focusing on downside risk." },
  lagged_return: { notation: "Pₜ₋ₛ ÷ Pₜ₋ₗ − 1", zh: "衡量较早区间的累计收益，并跳过最近一段时间以分离短期反转。", en: "Cumulative return over an older interval, skipping the most recent period to separate short-term reversal." },
  maximum_drawdown: { notation: "|min(Pₜ ÷ running max(P) − 1)|", zh: "窗口内价格相对此前峰值的最大跌幅。", en: "Largest peak-to-trough decline inside the window." },
  moving_average_ratio: { notation: "SMA(P, s) ÷ SMA(P, l) − 1", zh: "比较短期与长期均价；正值表示短期价格水平更强。", en: "Compares short- and long-window average prices; a positive value indicates stronger recent price levels." },
  ppo_histogram: { notation: "PPO − EMA(PPO, signal)", zh: "比较快慢指数均线的百分比差，再减去其信号线，用于观察趋势加速或减速。", en: "Percentage difference between fast and slow EMAs minus its signal line, indicating trend acceleration or deceleration." },
  realized_volatility: { notation: "stdev(rₜ, w) × √252", zh: "窗口内对数收益的样本标准差，并按 252 个交易日年化。", en: "Sample standard deviation of log returns, annualized using 252 trading days." },
  relative_dollar_volume: { notation: "(Pₜ × Vₜ) ÷ mean(P × V, w) − 1", zh: "当前成交额相对窗口平均成交额的变化。", en: "Current dollar volume relative to its window average." },
  return_excess_kurtosis: { notation: "excess kurtosis(rₜ, w)", zh: "衡量收益分布厚尾程度；正态分布基准为 0。", en: "Measures return-distribution tail thickness; a normal distribution has value 0." },
  return_skewness: { notation: "skewness(rₜ, w)", zh: "衡量窗口收益分布的不对称程度；正值表示右尾更长。", en: "Measures return-distribution asymmetry; positive values indicate a longer right tail." },
  rsi: { notation: "100 − 100 ÷ (1 + avg gain ÷ avg loss)", zh: "Wilder 平滑后的上涨与下跌强度比，常用于识别超买、超卖或趋势强弱。", en: "Wilder-smoothed ratio of gains to losses, commonly used for overbought, oversold, or trend-strength signals." },
  total_return: { notation: "Pₜ ÷ Pₜ₋w − 1", zh: "当前复权价格相对窗口起点的累计收益。", en: "Cumulative adjusted-price return from the start of the window." },
  return_continuation: { notation: "rank(Pₜ ÷ Pₜ₋w − 1)", zh: "将区间累计收益转换为横截面连续强弱分数，用于比较资产的相对动量。", en: "Converts cumulative return into a continuous cross-sectional strength score." },
  golden_cross_event: { notation: "SMA₅₀,t > SMA₂₀₀,t and SMA₅₀,t₋₁ ≤ SMA₂₀₀,t₋₁", zh: "短期均线从下方穿越长期均线，表示经典的趋势转强事件。", en: "The short moving average crosses above the long moving average, a classic strengthening event." },
  death_cross_event: { notation: "SMA₅₀,t < SMA₂₀₀,t and SMA₅₀,t₋₁ ≥ SMA₂₀₀,t₋₁", zh: "短期均线从上方跌破长期均线，表示经典的趋势转弱事件。", en: "The short moving average crosses below the long moving average, a classic weakening event." },
  price_cross_above_ma: { notation: "Pₜ > SMA(P,w) and Pₜ₋₁ ≤ SMA(P,w)ₜ₋₁", zh: "价格从下方上穿指定窗口均线。", en: "Price crosses above its selected-window moving average." },
  price_cross_below_ma: { notation: "Pₜ < SMA(P,w) and Pₜ₋₁ ≥ SMA(P,w)ₜ₋₁", zh: "价格从上方下穿指定窗口均线。", en: "Price crosses below its selected-window moving average." },
  price_above_ma_state: { notation: "1[Pₜ > SMA(P,w)]", zh: "价格是否位于均线上方的状态变量。", en: "State indicator for price being above its moving average." },
  short_return_reversal: { notation: "−rank(Pₜ ÷ Pₜ₋w − 1)", zh: "对短期收益反向排序，用于研究短期超涨超跌后的均值回归。", en: "Reverse-ranks short-horizon returns to study mean reversion after temporary pressure." },
  low_volatility: { notation: "−rank(stdev(rₜ,w) × √252)", zh: "对年化波动率反向排序，数值越高代表相对更低的波动风险。", en: "Reverse-ranks annualized volatility so higher scores represent lower relative risk." },
  low_downside_risk: { notation: "−rank(DownsideDeviationₜ,w)", zh: "对下行波动率反向排序，偏好负收益波动更低的资产。", en: "Reverse-ranks downside deviation to prefer assets with lower negative-return volatility." },
  drawdown_resilience: { notation: "−rank(MaxDrawdownₜ,w)", zh: "对最大回撤反向排序，分数更高表示历史回撤相对更轻。", en: "Reverse-ranks maximum drawdown; higher scores indicate milder historical drawdowns." },
  low_illiquidity_quality: { notation: "−rank(Amihudₜ,w)", zh: "对 Amihud 非流动性反向排序，偏好交易冲击较低的资产。", en: "Reverse-ranks Amihud illiquidity to prefer lower-impact assets." },
  illiquidity_premium: { notation: "rank(Amihudₜ,w)", zh: "正向排列非流动性，用于研究承担较差流动性是否获得补偿。", en: "Ranks illiquidity positively to study compensation for holding harder-to-trade assets." },
};

const researchDescriptions: Record<string, { zh: string; en: string }> = {
  forward_rank_h5: { zh: "从下一共同开盘开始，计算恰好 5 个完整交易日的复权开盘收益，再转换为每日居中的横截面排名。", en: "Adjusted-open return over exactly five complete sessions, transformed to a daily centered cross-sectional rank." },
  forward_rank_h10: { zh: "从下一共同开盘开始，计算恰好 10 个完整交易日的复权开盘收益，再转换为每日居中的横截面排名。", en: "Adjusted-open return over exactly ten complete sessions, transformed to a daily centered cross-sectional rank." },
  forward_rank_h21: { zh: "从下一共同开盘开始，计算恰好 21 个完整交易日的复权开盘收益，再转换为每日居中的横截面排名。", en: "Adjusted-open return over exactly twenty-one complete sessions, transformed to a daily centered cross-sectional rank." },
  expanding_daily_ols_v1: { zh: "确定性的扩展窗口 OLS；仅使用已成熟标签，禁止随机切分，并生成严格样本外预测。", en: "Deterministic expanding walk-forward OLS with mature-label purge and no random split." },
  expanding_daily_ridge_alpha1_v1: { zh: "确定性的扩展窗口 Ridge（α=1）；仅使用已成熟标签，禁止随机切分。", en: "Deterministic expanding walk-forward Ridge with alpha 1, mature-label purge, and no random split." },
  expanding_daily_rf_balanced_v1: { zh: "受控深度与固定随机种子的随机森林稳健基线，采用成熟标签清除与严格样本外预测。", en: "Conservative deterministic random forest with bounded depth, mature-label purge, and strict out-of-sample prediction." },
  expanding_daily_rf_feature_subsample_v1: { zh: "随机森林特征采样方案；在每棵树中采样部分信号，以降低树之间的相关性。", en: "Random forest with feature subsampling to reduce correlation between trees under the same strict walk-forward policy." },
  expanding_daily_lightgbm_balanced_v1: { zh: "受控叶节点与深度的 LightGBM 稳健基线，采用成熟标签清除与严格样本外预测。", en: "Conservative deterministic LightGBM with bounded complexity, mature-label purge, and strict out-of-sample prediction." },
  expanding_daily_lightgbm_feature_subsample_v1: { zh: "LightGBM 特征采样与更强正则化方案，用于降低多信号输入下的过拟合风险。", en: "LightGBM with feature subsampling and stronger regularization to reduce overfitting across many signals." },
  expanding_daily_xgb_balanced_v1: { zh: "受控树深的确定性 CPU XGBoost 稳健基线，采用成熟标签清除与严格样本外预测。", en: "Conservative deterministic CPU histogram XGBoost with bounded depth, mature-label purge, and strict out-of-sample prediction." },
  expanding_daily_xgb_feature_subsample_v1: { zh: "XGBoost 列采样与更强正则化方案，用于降低多信号输入下的过拟合风险。", en: "CPU histogram XGBoost with column subsampling and stronger regularization under the same strict walk-forward policy." },
};

const chineseRationales: Record<string, string> = {
  "A directionally stable cross-sectional score can select the strongest assets at each planned rebalance.": "方向稳定的横截面综合分数可在每次计划调仓时选出相对最强的资产。",
  "A fixed defensive budget provides a transparent parity baseline without making a market-timing claim.": "固定防御预算提供透明、可重放的基准方案，不声称具备市场择时能力。",
  "The frozen v0.21 SPY MA200 tiers provide an explicit market-regime parity baseline.": "冻结的标普 500 二百日均线分档为市场状态判断提供明确、可重放的基准。",
  "The frozen v0.21 long-history defensive basket provides a parity allocation for researching a defensive sleeve.": "冻结的长历史防御篮子为研究防御资产袖套提供可重放的基准配置。",
  "A fixed defensive sleeve provides a transparent parity baseline.": "固定防御袖套提供透明、易解释的基准方案。",
  "The frozen v0.21 SPY MA200 tiers provide an explicit defensive parity baseline.": "冻结的标普 500 二百日均线分档提供明确的防御预算基准。",
  "No defensive sleeve is applied.": "不启用防御袖套，全部预算由风险资产策略分配。",
  "Session open is an explicit raw market observation.": "交易时段开盘价是未经加工的基础市场观测。",
  "Session high is an explicit raw market observation.": "交易时段最高价是未经加工的基础市场观测。",
  "Session low is an explicit raw market observation.": "交易时段最低价是未经加工的基础市场观测。",
  "Unadjusted session close preserves raw price and dollar-volume semantics.": "未复权收盘价保留真实价格与成交额计算口径。",
  "Adjusted close is the frozen price basis for legacy return calculations.": "复权收盘价是历史收益研究所使用的冻结价格基础。",
  "Raw share volume measures trading activity without silent adjustment.": "原始成交量衡量交易活跃度，不进行隐式调整。",
  "Cash distributions are explicit corporate-action inputs.": "现金分红作为明确的公司行动输入保存。",
  "Split ratios are explicit corporate-action inputs.": "拆股比例作为明确的公司行动输入保存。",
  "The three-month Treasury rate is the frozen cash and excess-return reference.": "三个月期美债利率作为现金收益与超额收益的冻结参考。",
  "A deeper relative drawdown can create rebound potential after forced selling or overreaction.": "相对回撤越深，越可能反映被迫卖出或过度反应，从而形成反弹空间。",
  "A fresh downward price/average crossing can mark trend deterioration.": "价格刚向下穿越均线，可能表示趋势开始恶化。",
  "A fresh upward price/average crossing can mark trend initiation.": "价格刚向上穿越均线，可能表示新趋势正在形成。",
  "A higher PPO histogram indicates positive normalized trend acceleration.": "PPO 柱状差越高，表示标准化后的上行趋势加速度越强。",
  "A higher short-to-long moving-average ratio represents stronger prevailing trend.": "短期均线相对长期均线越高，通常表示当前趋势越强。",
  "A histogram crossing above zero marks improving normalized trend acceleration.": "PPO 柱状差上穿零轴，表示标准化趋势加速度正在改善。",
  "A histogram crossing below zero marks deteriorating normalized trend acceleration.": "PPO 柱状差下穿零轴，表示标准化趋势加速度正在恶化。",
  "A shallower recent drawdown indicates stronger capital preservation and trend resilience.": "近期回撤越浅，通常表示资本保全能力和趋势韧性越强。",
  "Assets with lottery-like positive skew may be over-demanded, leaving relatively low-skew assets with a premium.": "具有彩票特征的高正偏资产可能被过度追捧，因此低偏度资产可能获得补偿性溢价。",
  "Concentrated extreme returns may identify an active regime shift whose relative direction can persist.": "极端收益集中出现可能意味着市场状态切换，其相对方向有时会延续。",
  "Elevated dollar volume can reflect stronger attention, participation and executable trend confirmation.": "成交额上升可能反映关注度、参与度和交易可执行性增强，并对趋势形成确认。",
  "Investors may require compensation for bearing relatively greater illiquidity.": "投资者承担更高的非流动性时，可能要求额外收益作为补偿。",
  "Lower downside deviation favors assets with less harmful return variability.": "较低的下行波动表示有害收益波动较少，因此在风险维度上更占优。",
  "Lower excess kurtosis represents fewer extreme-return observations and a more stable return distribution.": "较低的超额峰度表示极端收益出现得更少，收益分布相对更稳定。",
  "Lower price impact per dollar traded represents better liquidity and implementation quality.": "单位成交额造成的价格冲击越低，通常表示流动性和策略执行质量越好。",
  "Lower realized volatility can represent more efficient risk-adjusted exposure and the low-volatility effect.": "较低的已实现波动率可能代表更有效的风险调整后暴露，并对应低波动效应。",
  "Lower RSI represents greater relative oversold pressure and a possible rebound.": "RSI 越低，表示相对超卖压力越强，也可能孕育反弹。",
  "Persistently high RSI can represent relative leadership rather than immediate reversal.": "持续较高的 RSI 也可能表示相对强势，而不一定立即反转。",
  "Positive return asymmetry may identify upside-led risk-on leadership in a relative rotation context.": "正收益偏度可能识别出由上行收益主导、风险偏好更强的相对领先资产。",
  "Price above a widely followed moving average marks a positive trend state.": "价格位于广泛关注的移动平均线之上，表示当前处于正向趋势状态。",
  "Relative return strength may persist because information and capital adjust gradually.": "信息和资金的调整往往并非瞬间完成，因此相对收益强势可能延续。",
  "RSI at or above 70 is a conventional overbought state and bearish reversal warning.": "RSI 达到或超过 70 通常被视为超买，并构成看跌反转提醒。",
  "RSI at or below 30 is a conventional oversold state.": "RSI 达到或低于 30 通常被视为超卖状态。",
  "Skipping the most recent month separates medium-term continuation from short-term reversal.": "跳过最近一个月，有助于将中期动量延续与短期反转区分开。",
  "The 50-day average crossing above the 200-day average is a classic long-horizon trend event.": "50 日均线上穿 200 日均线，是经典的长期趋势转强事件。",
  "The 50-day average crossing below the 200-day average is a classic long-horizon deterioration event.": "50 日均线下穿 200 日均线，是经典的长期趋势恶化事件。",
  "Very recent relative underperformance may reverse after temporary price pressure or overreaction.": "近期相对弱势可能来自暂时价格压力或过度反应，随后存在反转可能。",
};

function language(value: string | undefined): Language {
  return value?.startsWith("zh") ? "zh-CN" : "en";
}

export function researchLabel(value: string | null | undefined, resolvedLanguage?: string): string {
  if (!value) return "—";
  const current = language(resolvedLanguage);
  const exact = labels[current][value];
  if (exact) return exact;
  if (value.startsWith("dimension_equal_weight__")) {
    const dimension = researchLabel(value.split("__")[1], resolvedLanguage);
    return current === "zh-CN" ? `${dimension}维度等权模型` : `${dimension} equal-weight model`;
  }
  if (value.startsWith("pre_selection_trend_eligible_top_k__k")) {
    const k = value.split("__k")[1];
    return current === "zh-CN" ? `趋势过滤后选取 Top-${k}` : `Trend-filtered Top-${k}`;
  }
  if (value.startsWith("top_k_equal_weight__k")) {
    const k = value.split("__k")[1];
    return current === "zh-CN" ? `Top-${k} 等权` : `Top-${k} equal weight`;
  }
  return value.replaceAll("_", " ").replace(/\b\w/g, (letter) => letter.toUpperCase());
}

export function researchRationale(value: string, resolvedLanguage?: string): string {
  return language(resolvedLanguage) === "zh-CN" ? chineseRationales[value] ?? value : value;
}

export function researchDescription(key: string, fallback: string, resolvedLanguage?: string): string {
  const copy = researchDescriptions[key];
  return copy ? copy[language(resolvedLanguage) === "zh-CN" ? "zh" : "en"] : fallback;
}

export function ResearchKey({ value, className = "" }: { value: string | null | undefined; className?: string }) {
  const { i18n } = useTranslation();
  if (!value) return <span className={className}>—</span>;
  const label = researchLabel(value, i18n.resolvedLanguage);
  return <span className={`research-key ${className}`.trim()}><span>{label}</span>{label !== value && <code>{value}</code>}</span>;
}

export function FormulaDisplay({ factorKey, formula }: { factorKey: string; formula: string }) {
  const { t, i18n } = useTranslation();
  const guide = formulaGuides[factorKey];
  const current = language(i18n.resolvedLanguage);
  if (!guide) return <code className="formula-raw">{formula}</code>;
  return <div className="formula-display" aria-label={`${researchLabel(factorKey, i18n.resolvedLanguage)}: ${guide.notation}`}>
    <div className="formula-notation"><span>{t("common.formula")}</span><strong>{guide.notation}</strong></div>
    <p>{guide[current === "zh-CN" ? "zh" : "en"]}</p>
    <details><summary>{t("common.rawDefinition")}</summary><code>{formula}</code></details>
  </div>;
}
