/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v2/artifacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Artifacts */
        get: operations["artifacts_api_v2_artifacts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/artifacts/{artifact_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Artifact Detail */
        get: operations["artifact_detail_api_v2_artifacts__artifact_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/artifacts/{artifact_id}/lineage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lineage */
        get: operations["lineage_api_v2_artifacts__artifact_id__lineage_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Capabilities */
        get: operations["capabilities_api_v2_capabilities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/catalog/assets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Asset Catalog */
        get: operations["asset_catalog_api_v2_catalog_assets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/catalog/data-requirements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Data Requirements */
        get: operations["data_requirements_api_v2_catalog_data_requirements_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/compare/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Product Compare */
        get: operations["product_compare_api_v2_compare_products_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/data/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Data Overview */
        get: operations["data_overview_api_v2_data_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/experiments/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Experiment Overview */
        get: operations["experiment_overview_api_v2_experiments_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/experiments/results/{artifact_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Experiment Result */
        get: operations["experiment_result_api_v2_experiments_results__artifact_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/experiments/results/{artifact_id}/decisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Decision Explorer */
        get: operations["decision_explorer_api_v2_experiments_results__artifact_id__decisions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/factors/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Factor Overview */
        get: operations["factor_overview_api_v2_factors_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v2_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/models/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Model Overview */
        get: operations["model_overview_api_v2_models_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/rankings/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Product Ranking */
        get: operations["product_ranking_api_v2_rankings_products_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/signals/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Signal Overview */
        get: operations["signal_overview_api_v2_signals_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/strategies/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Strategy Overview */
        get: operations["strategy_overview_api_v2_strategies_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/strategies/targets/{artifact_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Strategy Target Path */
        get: operations["strategy_target_path_api_v2_strategies_targets__artifact_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ApiContext */
        ApiContext: {
            /**
             * Api Version
             * @default v2
             * @constant
             */
            api_version: "v2";
            /**
             * Read Only
             * @default true
             * @constant
             */
            read_only: true;
            /** System Version */
            system_version: string;
        };
        /** ArtifactDetailResponse */
        ArtifactDetailResponse: {
            artifact: components["schemas"]["ArtifactSummary"];
            context: components["schemas"]["ApiContext"];
            /** Direct Dependencies */
            direct_dependencies: components["schemas"]["DependencySummary"][];
            /** Direct Dependents */
            direct_dependents: components["schemas"]["DependencySummary"][];
            /** Lineage Url */
            lineage_url: string | null;
            quality: components["schemas"]["QualitySummary"];
        };
        /** ArtifactListResponse */
        ArtifactListResponse: {
            context: components["schemas"]["ApiContext"];
            /** Items */
            items: components["schemas"]["ArtifactSummary"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            quality: components["schemas"]["QualitySummary"];
            /** Total */
            total: number;
        };
        /** ArtifactSummary */
        ArtifactSummary: {
            /**
             * Artifact Id
             * Format: uuid
             */
            artifact_id: string;
            /** Artifact Key */
            artifact_key: string;
            /** Artifact Type */
            artifact_type: string;
            /** Content Hash */
            content_hash: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Published At */
            published_at: string | null;
            quality: components["schemas"]["QualitySummary"];
            /** Semantic Fingerprint */
            semantic_fingerprint: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "draft" | "published" | "retired" | "superseded" | "invalidated" | "tainted";
            /** Version Number */
            version_number: number;
        };
        /** AssetCatalogItem */
        AssetCatalogItem: {
            /**
             * Asset Id
             * Format: uuid
             */
            asset_id: string;
            /** Asset Key */
            asset_key: string;
            /** Asset Type */
            asset_type: string;
            /** Calendar Key */
            calendar_key: string;
            /** Classifications */
            classifications: {
                [key: string]: string;
            };
            /** Currency */
            currency: string;
            /** Name */
            name: string;
            /** Status */
            status: string;
            /** Symbol */
            symbol: string;
            /** Timezone */
            timezone: string;
            /** Universe Ordinal */
            universe_ordinal: number | null;
            /** Universe Role */
            universe_role: string | null;
            /** Venue Mic */
            venue_mic: string;
        };
        /** AssetCatalogResponse */
        AssetCatalogResponse: {
            /** As Of Date */
            as_of_date: string;
            context: components["schemas"]["ApiContext"];
            /** Items */
            items: components["schemas"]["AssetCatalogItem"][];
            quality: components["schemas"]["QualitySummary"];
            /**
             * Release Artifact Id
             * Format: uuid
             */
            release_artifact_id: string;
            /** Release Version Number */
            release_version_number: number;
            /** Universe Key */
            universe_key: string;
        };
        /** CapabilitiesResponse */
        CapabilitiesResponse: {
            context: components["schemas"]["ApiContext"];
            /** Domains */
            domains: components["schemas"]["DomainCapability"][];
            /** Endpoints */
            endpoints: string[];
            /** Interface States */
            interface_states: string[];
            /** Languages */
            languages: ("zh-CN" | "en")[];
            quality: components["schemas"]["QualitySummary"];
        };
        /** ComparisonCohortItem */
        ComparisonCohortItem: {
            /**
             * Artifact Id
             * Format: uuid
             */
            artifact_id: string;
            /**
             * As Of Date
             * Format: date
             */
            as_of_date: string;
            /** Benchmark Key */
            benchmark_key: string;
            /** Cohort Key */
            cohort_key: string;
            /**
             * Common Data Ready Date
             * Format: date
             */
            common_data_ready_date: string;
            /**
             * Common Metric End
             * Format: date
             */
            common_metric_end: string;
            /**
             * Common Metric Start
             * Format: date
             */
            common_metric_start: string;
            /**
             * Common Simulation Start
             * Format: date
             */
            common_simulation_start: string;
            /** Context Fingerprint */
            context_fingerprint: string;
            /** Cost Bps Per Side */
            cost_bps_per_side: number;
            /**
             * Currency
             * @constant
             */
            currency: "USD";
            /** Description */
            description: string;
            /**
             * Frequency
             * @enum {string}
             */
            frequency: "weekly" | "monthly";
            /** Initialization Policy */
            initialization_policy: string;
            /** Member Count */
            member_count: number;
            /** Name */
            name: string;
            /** Required Warmup Observations */
            required_warmup_observations: number;
            /** Target K */
            target_k: number;
            /** Template Key */
            template_key: string;
            /** Version Number */
            version_number: number;
        };
        /** DataBundleItem */
        DataBundleItem: {
            /**
             * Artifact Id
             * Format: uuid
             */
            artifact_id: string;
            /** Bundle Key */
            bundle_key: string;
            /**
             * Coverage End
             * Format: date
             */
            coverage_end: string;
            /**
             * Coverage Start
             * Format: date
             */
            coverage_start: string;
            /** Member Count */
            member_count: number;
            /** Members */
            members: components["schemas"]["DataBundleMemberItem"][];
            /** Name */
            name: string;
            /** Version Number */
            version_number: number;
        };
        /** DataBundleMemberItem */
        DataBundleMemberItem: {
            /**
             * Artifact Id
             * Format: uuid
             */
            artifact_id: string;
            /** Artifact Key */
            artifact_key: string;
            /** Artifact Type */
            artifact_type: string;
            /** Ordinal */
            ordinal: number;
            /** Role */
            role: string;
            /** Version Number */
            version_number: number;
        };
        /** DataOverviewResponse */
        DataOverviewResponse: {
            bundle: components["schemas"]["DataBundleItem"] | null;
            context: components["schemas"]["ApiContext"];
            /** Datasets */
            datasets: components["schemas"]["DatasetPublicationItem"][];
            eligibility: components["schemas"]["EligibilitySnapshotItem"] | null;
            quality: components["schemas"]["QualitySummary"];
            /** Sources */
            sources: components["schemas"]["SourceSnapshotItem"][];
        };
        /** DataQualityIssueItem */
        DataQualityIssueItem: {
            /** Asset Key */
            asset_key: string | null;
            /** Details */
            details: {
                [key: string]: unknown;
            };
            /** Event Date */
            event_date: string | null;
            /** Message */
            message: string;
            /** Rule Code */
            rule_code: string;
            /**
             * Severity
             * @enum {string}
             */
            severity: "info" | "warning" | "error";
        };
        /** DataRequirementItem */
        DataRequirementItem: {
            /** Calendar Type */
            calendar_type: string;
            /** Fields */
            fields: string[];
            /** Interval Count */
            interval_count: number;
            /** Interval Unit */
            interval_unit: string;
            /** Requirement Key */
            requirement_key: string;
            /** Series Key */
            series_key: string;
            /** Session Type */
            session_type: string;
            /** Subject */
            subject: string;
            /** Timestamp Semantics */
            timestamp_semantics: string;
        };
        /** DataRequirementResponse */
        DataRequirementResponse: {
            /**
             * Artifact Id
             * Format: uuid
             */
            artifact_id: string;
            context: components["schemas"]["ApiContext"];
            /** Items */
            items: components["schemas"]["DataRequirementItem"][];
            quality: components["schemas"]["QualitySummary"];
            /** Requirement Set Key */
            requirement_set_key: string;
            /** Version Number */
            version_number: number;
        };
        /** DatasetCoverageItem */
        DatasetCoverageItem: {
            /** Asset Key */
            asset_key: string | null;
            /**
             * Coverage End
             * Format: date
             */
            coverage_end: string;
            /**
             * Coverage Start
             * Format: date
             */
            coverage_start: string;
            /** Missing Count */
            missing_count: number;
            /** Observation Count */
            observation_count: number;
            /** Subject Key */
            subject_key: string;
        };
        /** DatasetPublicationItem */
        DatasetPublicationItem: {
            /**
             * Artifact Id
             * Format: uuid
             */
            artifact_id: string;
            /** Coverage */
            coverage: components["schemas"]["DatasetCoverageItem"][];
            /**
             * Coverage End
             * Format: date
             */
            coverage_end: string;
            /**
             * Coverage Start
             * Format: date
             */
            coverage_start: string;
            /** Dataset Key */
            dataset_key: string;
            /**
             * Dataset Kind
             * @enum {string}
             */
            dataset_kind: "canonical" | "derived";
            /** Issues */
            issues: components["schemas"]["DataQualityIssueItem"][];
            quality: components["schemas"]["QualitySummary"];
            /** Row Count */
            row_count: number;
            /**
             * Value Kind
             * @enum {string}
             */
            value_kind: "daily_bar" | "rate_observation" | "reserve_return";
            /** Version Number */
            version_number: number;
        };
        /** DecisionComponentTraceItem */
        DecisionComponentTraceItem: {
            /** Component Weight */
            component_weight: number;
            /**
             * Data Bundle Artifact Id
             * Format: uuid
             */
            data_bundle_artifact_id: string;
            /** Dimension Key */
            dimension_key: string;
            /** Dimension Weight */
            dimension_weight: number;
            /**
             * Factor Dataset Artifact Id
             * Format: uuid
             */
            factor_dataset_artifact_id: string;
            /** Factor Key */
            factor_key: string;
            /** Factor Value */
            factor_value: number;
            /** Factor Variant Key */
            factor_variant_key: string;
            /** Input Transform */
            input_transform: string;
            /** Overall Contribution */
            overall_contribution: number | null;
            /**
             * Signal Dataset Artifact Id
             * Format: uuid
             */
            signal_dataset_artifact_id: string;
            /** Signal Key */
            signal_key: string;
            /** Signal Score */
            signal_score: number;
            /** Signal State */
            signal_state: string | null;
            /**
             * Signal Version Artifact Id
             * Format: uuid
             */
            signal_version_artifact_id: string;
            /** Transformed Signal Score */
            transformed_signal_score: number;
            /** Weighted Component Input */
            weighted_component_input: number;
        };
        /** DecisionExplorerResponse */
        DecisionExplorerResponse: {
            /** Actual Holding Count */
            actual_holding_count: number;
            /** Available Dates */
            available_dates: string[];
            context: components["schemas"]["ApiContext"];
            /**
             * Data Bundle Artifact Id
             * Format: uuid
             */
            data_bundle_artifact_id: string;
            /**
             * Eligibility Artifact Id
             * Format: uuid
             */
            eligibility_artifact_id: string;
            /**
             * Model Dataset Artifact Id
             * Format: uuid
             */
            model_dataset_artifact_id: string;
            /** Model Method Key */
            model_method_key: string;
            /**
             * Model Specification Artifact Id
             * Format: uuid
             */
            model_specification_artifact_id: string;
            /** Positions */
            positions: components["schemas"]["DecisionPositionTraceItem"][];
            quality: components["schemas"]["QualitySummary"];
            /** Reserve Target Weight */
            reserve_target_weight: number;
            /**
             * Result Artifact Id
             * Format: uuid
             */
            result_artifact_id: string;
            /**
             * Selected Date
             * Format: date
             */
            selected_date: string;
            /** Target K */
            target_k: number;
            /**
             * Target Path Artifact Id
             * Format: uuid
             */
            target_path_artifact_id: string;
            /**
             * Universe Artifact Id
             * Format: uuid
             */
            universe_artifact_id: string;
        };
        /** DecisionPositionTraceItem */
        DecisionPositionTraceItem: {
            /** Asset Key */
            asset_key: string;
            /** Components */
            components: components["schemas"]["DecisionComponentTraceItem"][];
            /** Decision Reason */
            decision_reason: string;
            /** Model Rank */
            model_rank: number;
            /** Model Score */
            model_score: number;
            /** Selected */
            selected: boolean;
            /** Symbol */
            symbol: string;
            /** Target Weight */
            target_weight: number;
            /** Trend State */
            trend_state: string | null;
        };
        /** DependencySummary */
        DependencySummary: {
            /**
             * Artifact Id
             * Format: uuid
             */
            artifact_id: string;
            /**
             * Depends On Artifact Id
             * Format: uuid
             */
            depends_on_artifact_id: string;
            /** Ordinal */
            ordinal: number | null;
            /** Role */
            role: string;
        };
        /** DomainCapability */
        DomainCapability: {
            /**
             * Availability
             * @enum {string}
             */
            availability: "available" | "planned";
            /** Delivery Milestone */
            delivery_milestone: string;
            /** Key */
            key: string;
            /** Purpose */
            purpose: string;
            /** Upstream */
            upstream: string[];
        };
        /** EligibilityAssetItem */
        EligibilityAssetItem: {
            /**
             * Asset Id
             * Format: uuid
             */
            asset_id: string;
            /** Asset Key */
            asset_key: string;
            /** Available End */
            available_end: string | null;
            /** Available Start */
            available_start: string | null;
            /** Data Ready Date */
            data_ready_date: string | null;
            /** Is Eligible */
            is_eligible: boolean;
            /** Issues */
            issues: components["schemas"]["EligibilityIssueItem"][];
            /** Observation Count */
            observation_count: number;
            /** Role */
            role: string;
            /** Symbol */
            symbol: string;
        };
        /** EligibilityIssueItem */
        EligibilityIssueItem: {
            /** Details */
            details: {
                [key: string]: unknown;
            };
            /** Issue Code */
            issue_code: string;
            /** Message */
            message: string;
            /**
             * Severity
             * @enum {string}
             */
            severity: "warning" | "error";
        };
        /** EligibilitySnapshotItem */
        EligibilitySnapshotItem: {
            /**
             * Artifact Id
             * Format: uuid
             */
            artifact_id: string;
            /** Eligible Count */
            eligible_count: number;
            /** Items */
            items: components["schemas"]["EligibilityAssetItem"][];
            /** Member Count */
            member_count: number;
            /**
             * Requested End
             * Format: date
             */
            requested_end: string;
            /**
             * Requested Start
             * Format: date
             */
            requested_start: string;
            /** Snapshot Key */
            snapshot_key: string;
            /** Warmup Observations */
            warmup_observations: number;
        };
        /** ExperimentArtifactLinkItem */
        ExperimentArtifactLinkItem: {
            /**
             * Artifact Id
             * Format: uuid
             */
            artifact_id: string;
            /** Artifact Key */
            artifact_key: string;
            /** Artifact Type */
            artifact_type: string;
            /** Role */
            role: string;
        };
        /** ExperimentMetricItem */
        ExperimentMetricItem: {
            /** Metric Key */
            metric_key: string;
            /**
             * Metric Scope
             * @enum {string}
             */
            metric_scope: "absolute" | "relative";
            /** Name */
            name: string;
            /** Observation Count */
            observation_count: number;
            /** Reason Code */
            reason_code: string | null;
            /**
             * Series Role
             * @enum {string}
             */
            series_role: "strategy" | "benchmark" | "relative";
            /** Unit */
            unit: string;
            /** Value */
            value: number | null;
            /** Value Status */
            value_status: string;
        };
        /** ExperimentOverviewResponse */
        ExperimentOverviewResponse: {
            context: components["schemas"]["ApiContext"];
            quality: components["schemas"]["QualitySummary"];
            /** Specifications */
            specifications: components["schemas"]["ExperimentSpecificationItem"][];
            /** Suites */
            suites: components["schemas"]["ExperimentSuiteItem"][];
        };
        /** ExperimentQualityCheckItem */
        ExperimentQualityCheckItem: {
            /** Check Key */
            check_key: string;
            /** Message */
            message: string;
            /** Scope Key */
            scope_key: string;
            /** Severity */
            severity: string;
            /** Status */
            status: string;
        };
        /** ExperimentResultResponse */
        ExperimentResultResponse: {
            /** Artifacts */
            artifacts: components["schemas"]["ExperimentArtifactLinkItem"][];
            /** Completed At */
            completed_at: string | null;
            context: components["schemas"]["ApiContext"];
            /** Events */
            events: components["schemas"]["ExperimentRunEventItem"][];
            /**
             * Interval Result Artifact Id
             * Format: uuid
             */
            interval_result_artifact_id: string;
            /** Metric Value Count */
            metric_value_count: number;
            /** Metrics */
            metrics: components["schemas"]["ExperimentMetricItem"][];
            /** Normalization Nav Date */
            normalization_nav_date: string | null;
            /** Observation Count */
            observation_count: number;
            quality: components["schemas"]["QualitySummary"];
            /** Quality Checks */
            quality_checks: components["schemas"]["ExperimentQualityCheckItem"][];
            /**
             * Requested End
             * Format: date
             */
            requested_end: string;
            /**
             * Requested Start
             * Format: date
             */
            requested_start: string;
            /** Resolved End */
            resolved_end: string | null;
            /** Resolved Start */
            resolved_start: string | null;
            /**
             * Result Artifact Id
             * Format: uuid
             */
            result_artifact_id: string;
            /**
             * Run Attempt Id
             * Format: uuid
             */
            run_attempt_id: string;
            /** Run Status */
            run_status: string;
            specification: components["schemas"]["ExperimentSpecificationItem"];
            /** Started At */
            started_at: string | null;
        };
        /** ExperimentRunEventItem */
        ExperimentRunEventItem: {
            /** Event Type */
            event_type: string;
            /** Message */
            message: string;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            /** Sequence Number */
            sequence_number: number;
            /** Severity */
            severity: string;
        };
        /** ExperimentSpecificationItem */
        ExperimentSpecificationItem: {
            /**
             * Artifact Id
             * Format: uuid
             */
            artifact_id: string;
            /**
             * As Of Date
             * Format: date
             */
            as_of_date: string;
            /** Attempt Number */
            attempt_number: number | null;
            /** Availability Status */
            availability_status: string | null;
            /** Benchmark Category */
            benchmark_category: string;
            /** Benchmark Key */
            benchmark_key: string;
            /** Cell Key */
            cell_key: string;
            /** Core Metrics */
            core_metrics: {
                [key: string]: number | null;
            };
            /** Cost Bps Per Side */
            cost_bps_per_side: number;
            /** Error Summary */
            error_summary: string | null;
            /**
             * Frequency
             * @enum {string}
             */
            frequency: "weekly" | "monthly";
            /** Initialization Policy */
            initialization_policy: string;
            /** Model Specification Key */
            model_specification_key: string;
            /** Ordinal */
            ordinal: number;
            /** Product Key */
            product_key: string;
            /** Quality Status */
            quality_status: string | null;
            /** Result Artifact Id */
            result_artifact_id: string | null;
            /**
             * Simulation End
             * Format: date
             */
            simulation_end: string;
            /**
             * Status
             * @enum {string}
             */
            status: "accepted" | "failed" | "running" | "pending";
            /**
             * Suite Artifact Id
             * Format: uuid
             */
            suite_artifact_id: string;
            /** Template Key */
            template_key: string;
            /** Variant Key */
            variant_key: string;
        };
        /** ExperimentSuiteItem */
        ExperimentSuiteItem: {
            /**
             * Artifact Id
             * Format: uuid
             */
            artifact_id: string;
            /** Description */
            description: string;
            /** Name */
            name: string;
            /** Specification Count */
            specification_count: number;
            /** Suite Key */
            suite_key: string;
            /** Version Number */
            version_number: number;
        };
        /** FactorCorrelationItem */
        FactorCorrelationItem: {
            /** High Correlation */
            high_correlation: boolean;
            /** Left Factor Key */
            left_factor_key: string;
            /** Left Variant Key */
            left_variant_key: string;
            /** Observation Count */
            observation_count: number;
            /** Right Factor Key */
            right_factor_key: string;
            /** Right Variant Key */
            right_variant_key: string;
            /** Same Definition */
            same_definition: boolean;
            /** Spearman Correlation */
            spearman_correlation: number | null;
        };
        /** FactorDatasetDiagnosticItem */
        FactorDatasetDiagnosticItem: {
            /** Asset Count */
            asset_count: number;
            /**
             * Coverage End
             * Format: date
             */
            coverage_end: string;
            /**
             * Coverage Start
             * Format: date
             */
            coverage_start: string;
            /**
             * Factor Dataset Artifact Id
             * Format: uuid
             */
            factor_dataset_artifact_id: string;
            /** Factor Key */
            factor_key: string;
            /** Formula */
            formula: string;
            /** Maximum */
            maximum: number;
            /** Mean */
            mean: number;
            /** Measurement Family */
            measurement_family: string;
            /** Median */
            median: number;
            /** Minimum */
            minimum: number;
            /** Missing Count */
            missing_count: number;
            /** Observation Count */
            observation_count: number;
            /** Output Unit */
            output_unit: string;
            /** P05 */
            p05: number;
            /** P25 */
            p25: number;
            /** P75 */
            p75: number;
            /** P95 */
            p95: number;
            /** Parameters */
            parameters: {
                [key: string]: unknown;
            };
            /** Preset Type */
            preset_type: string;
            quality: components["schemas"]["QualitySummary"];
            /** Row Count */
            row_count: number;
            /** Standard Deviation */
            standard_deviation: number;
            /** Variant Key */
            variant_key: string;
            /** Zero Variance */
            zero_variance: boolean;
        };
        /** FactorDiagnosticIssueItem */
        FactorDiagnosticIssueItem: {
            /** Details */
            details: {
                [key: string]: unknown;
            };
            /** Issue Code */
            issue_code: string;
            /** Message */
            message: string;
            /**
             * Severity
             * @enum {string}
             */
            severity: "info" | "warning" | "error";
            /** Variant Key */
            variant_key: string;
        };
        /** FactorOverviewResponse */
        FactorOverviewResponse: {
            /** Asset Count */
            asset_count: number;
            context: components["schemas"]["ApiContext"];
            /** Correlations */
            correlations: components["schemas"]["FactorCorrelationItem"][];
            /**
             * Coverage End
             * Format: date
             */
            coverage_end: string;
            /**
             * Coverage Start
             * Format: date
             */
            coverage_start: string;
            /**
             * Data Bundle Artifact Id
             * Format: uuid
             */
            data_bundle_artifact_id: string;
            /** Dataset Count */
            dataset_count: number;
            /** Datasets */
            datasets: components["schemas"]["FactorDatasetDiagnosticItem"][];
            /**
             * Diagnostic Artifact Id
             * Format: uuid
             */
            diagnostic_artifact_id: string;
            /**
             * Diagnostic Engine Artifact Id
             * Format: uuid
             */
            diagnostic_engine_artifact_id: string;
            /**
             * Eligibility Artifact Id
             * Format: uuid
             */
            eligibility_artifact_id: string;
            /**
             * Factor Catalog Artifact Id
             * Format: uuid
             */
            factor_catalog_artifact_id: string;
            /**
             * Factor Engine Artifact Id
             * Format: uuid
             */
            factor_engine_artifact_id: string;
            /** High Correlation Threshold */
            high_correlation_threshold: number;
            /** Issues */
            issues: components["schemas"]["FactorDiagnosticIssueItem"][];
            /** Observation Count */
            observation_count: number;
            /** Pair Count */
            pair_count: number;
            quality: components["schemas"]["QualitySummary"];
            /**
             * Universe Artifact Id
             * Format: uuid
             */
            universe_artifact_id: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            context: components["schemas"]["ApiContext"];
            /** Database Revision */
            database_revision: string | null;
            quality: components["schemas"]["QualitySummary"];
        };
        /** LineageManifestResponse */
        LineageManifestResponse: {
            /** Artifacts */
            artifacts: {
                [key: string]: unknown;
            }[];
            /** Canonical Version */
            canonical_version: string;
            context: components["schemas"]["ApiContext"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Dependencies */
            dependencies: components["schemas"]["DependencySummary"][];
            /** Manifest Hash */
            manifest_hash: string;
            quality: components["schemas"]["QualitySummary"];
            root_artifact: components["schemas"]["ArtifactSummary"];
        };
        /** ModelAblationItem */
        ModelAblationItem: {
            /** Ablated Specification Key */
            ablated_specification_key: string;
            /** Delta Information Ratio */
            delta_information_ratio: number | null;
            /** Delta Mean Rank Ic */
            delta_mean_rank_ic: number | null;
            /** Delta Mean Top Bottom Spread */
            delta_mean_top_bottom_spread: number;
            /** Full Specification Key */
            full_specification_key: string;
            /** Period Count */
            period_count: number;
            /** Removed Dimension Key */
            removed_dimension_key: string;
            /** Window Key */
            window_key: string;
        };
        /** ModelComponentItem */
        ModelComponentItem: {
            /** Input Transform */
            input_transform: string;
            /** Signal Key */
            signal_key: string;
            /** Weight */
            weight: number;
        };
        /** ModelDiagnosticIssueItem */
        ModelDiagnosticIssueItem: {
            /** Details */
            details: {
                [key: string]: unknown;
            };
            /** Issue Code */
            issue_code: string;
            /** Message */
            message: string;
            /**
             * Severity
             * @enum {string}
             */
            severity: "info" | "warning" | "error";
            /** Specification Key */
            specification_key: string;
        };
        /** ModelDiagnosticItem */
        ModelDiagnosticItem: {
            /** Active Dimension Count */
            active_dimension_count: number;
            /** Component Count */
            component_count: number;
            /** Dimensions */
            dimensions: components["schemas"]["ModelDimensionItem"][];
            full: components["schemas"]["ModelWindowMetricItem"];
            /** Hypothesis */
            hypothesis: string;
            /**
             * Model Dataset Artifact Id
             * Format: uuid
             */
            model_dataset_artifact_id: string;
            /** Model Family */
            model_family: string;
            /** Model Key */
            model_key: string;
            /** Output Type */
            output_type: string;
            /** Overall Method Key */
            overall_method_key: string;
            quality: components["schemas"]["QualitySummary"];
            /** Research Tier */
            research_tier: string;
            /** Specification Key */
            specification_key: string;
            /** Specification Type */
            specification_type: string;
            /** Stability */
            stability: components["schemas"]["ModelWindowMetricItem"][];
            /** Tie Output */
            tie_output: string;
        };
        /** ModelDimensionItem */
        ModelDimensionItem: {
            /** Components */
            components: components["schemas"]["ModelComponentItem"][];
            /** Dimension Key */
            dimension_key: string;
            /** Input Transform */
            input_transform: string;
            /** Method Key */
            method_key: string;
            /** Weight */
            weight: number;
        };
        /** ModelOverviewResponse */
        ModelOverviewResponse: {
            /** Ablation Count */
            ablation_count: number;
            /** Ablations */
            ablations: components["schemas"]["ModelAblationItem"][];
            /** Common Period Count */
            common_period_count: number;
            context: components["schemas"]["ApiContext"];
            /**
             * Coverage End
             * Format: date
             */
            coverage_end: string;
            /**
             * Coverage Start
             * Format: date
             */
            coverage_start: string;
            /**
             * Data Bundle Artifact Id
             * Format: uuid
             */
            data_bundle_artifact_id: string;
            /**
             * Eligibility Artifact Id
             * Format: uuid
             */
            eligibility_artifact_id: string;
            /**
             * Evaluation Artifact Id
             * Format: uuid
             */
            evaluation_artifact_id: string;
            /**
             * Evaluation Engine Artifact Id
             * Format: uuid
             */
            evaluation_engine_artifact_id: string;
            /**
             * Forward Return Artifact Id
             * Format: uuid
             */
            forward_return_artifact_id: string;
            /**
             * Frequency
             * @enum {string}
             */
            frequency: "weekly" | "monthly";
            /** High Correlation Threshold */
            high_correlation_threshold: number;
            /** Issues */
            issues: components["schemas"]["ModelDiagnosticIssueItem"][];
            /**
             * Model Catalog Artifact Id
             * Format: uuid
             */
            model_catalog_artifact_id: string;
            /** Model Count */
            model_count: number;
            /**
             * Model Engine Artifact Id
             * Format: uuid
             */
            model_engine_artifact_id: string;
            /** Models */
            models: components["schemas"]["ModelDiagnosticItem"][];
            /** Pair Count */
            pair_count: number;
            /** Pairs */
            pairs: components["schemas"]["ModelPairDiagnosticItem"][];
            quality: components["schemas"]["QualitySummary"];
            /** Target Key */
            target_key: string;
            /**
             * Universe Artifact Id
             * Format: uuid
             */
            universe_artifact_id: string;
        };
        /** ModelPairDiagnosticItem */
        ModelPairDiagnosticItem: {
            /** High Correlation */
            high_correlation: boolean;
            /** Left Specification Key */
            left_specification_key: string;
            /** Mean Top2 Overlap */
            mean_top2_overlap: number;
            /** Right Specification Key */
            right_specification_key: string;
            /** Score Observation Count */
            score_observation_count: number;
            /** Score Spearman */
            score_spearman: number | null;
            /** Spread Correlation */
            spread_correlation: number | null;
            /** Spread Period Count */
            spread_period_count: number;
        };
        /** ModelWindowMetricItem */
        ModelWindowMetricItem: {
            /** Information Ratio */
            information_ratio: number | null;
            /** Mean Confidence */
            mean_confidence: number;
            /** Mean Rank Ic */
            mean_rank_ic: number | null;
            /** Mean Score Dispersion */
            mean_score_dispersion: number;
            /** Mean Top2 Turnover */
            mean_top2_turnover: number | null;
            /** Mean Top Bottom Spread */
            mean_top_bottom_spread: number;
            /** Median Rank Ic */
            median_rank_ic: number | null;
            /** Non Neutral Rate */
            non_neutral_rate: number;
            /** Period Count */
            period_count: number;
            /** Positive Ic Ratio */
            positive_ic_ratio: number | null;
            /** Undefined Ic Count */
            undefined_ic_count: number;
            /** Valid Ic Count */
            valid_ic_count: number;
            /**
             * Window End
             * Format: date
             */
            window_end: string;
            /** Window Key */
            window_key: string;
            /**
             * Window Start
             * Format: date
             */
            window_start: string;
        };
        /** ProductCompareEntry */
        ProductCompareEntry: {
            /** Availability Status */
            availability_status: string;
            /** Cost Bps Per Side */
            cost_bps_per_side: number;
            /**
             * Frequency
             * @enum {string}
             */
            frequency: "weekly" | "monthly";
            /** Initialization Policy */
            initialization_policy: string;
            /** Metrics */
            metrics: components["schemas"]["ExperimentMetricItem"][];
            /** Model Specification Key */
            model_specification_key: string;
            /** Product Key */
            product_key: string;
            /** Quality Status */
            quality_status: string;
            /** Resolved End */
            resolved_end: string | null;
            /** Resolved Start */
            resolved_start: string | null;
            /**
             * Result Artifact Id
             * Format: uuid
             */
            result_artifact_id: string;
            /** Strategy Template Key */
            strategy_template_key: string;
            /** Target K */
            target_k: number;
            /** Template Key */
            template_key: string;
            /** Variant Key */
            variant_key: string;
        };
        /** ProductCompareResponse */
        ProductCompareResponse: {
            /** Blocking Context Fields */
            blocking_context_fields: string[];
            /** Changed Dimensions */
            changed_dimensions: string[];
            context: components["schemas"]["ApiContext"];
            /** Entries */
            entries: components["schemas"]["ProductCompareEntry"][];
            /**
             * Mode
             * @enum {string}
             */
            mode: "controlled" | "side_by_side" | "identical";
            quality: components["schemas"]["QualitySummary"];
        };
        /** ProductRankingEntry */
        ProductRankingEntry: {
            /** Core Metrics */
            core_metrics: {
                [key: string]: number | null;
            };
            /**
             * Frequency
             * @enum {string}
             */
            frequency: "weekly" | "monthly";
            /** Metric Value */
            metric_value: number | null;
            /** Model Specification Key */
            model_specification_key: string;
            /** Observation Count */
            observation_count: number;
            /**
             * Product Artifact Id
             * Format: uuid
             */
            product_artifact_id: string;
            /** Product Key */
            product_key: string;
            /** Rank */
            rank: number | null;
            /** Reason Code */
            reason_code: string | null;
            /**
             * Result Artifact Id
             * Format: uuid
             */
            result_artifact_id: string;
            /** Target K */
            target_k: number;
            /** Value Status */
            value_status: string;
            /** Variant Key */
            variant_key: string;
        };
        /** ProductRankingResponse */
        ProductRankingResponse: {
            /** Active Cohort Artifact Id */
            active_cohort_artifact_id: string | null;
            /** Candidate Count */
            candidate_count: number;
            /** Cohorts */
            cohorts: components["schemas"]["ComparisonCohortItem"][];
            context: components["schemas"]["ApiContext"];
            /** Entries */
            entries: components["schemas"]["ProductRankingEntry"][];
            quality: components["schemas"]["QualitySummary"];
            /** Ranked Count */
            ranked_count: number;
            /**
             * Ranking Direction
             * @enum {string}
             */
            ranking_direction: "higher_is_better" | "lower_is_better";
            /** Selected Metric */
            selected_metric: string;
        };
        /** QualitySummary */
        QualitySummary: {
            /** Codes */
            codes?: string[];
            /**
             * State
             * @enum {string}
             */
            state: "ok" | "partial" | "warning" | "error";
        };
        /** SignalDiagnosticIssueItem */
        SignalDiagnosticIssueItem: {
            /** Details */
            details: {
                [key: string]: unknown;
            };
            /** Issue Code */
            issue_code: string;
            /** Message */
            message: string;
            /**
             * Severity
             * @enum {string}
             */
            severity: "info" | "warning" | "error";
            /** Signal Key */
            signal_key: string;
        };
        /** SignalDiagnosticItem */
        SignalDiagnosticItem: {
            /** Direction */
            direction: string;
            /** Economic Family */
            economic_family: string;
            /** Factor Variant Key */
            factor_variant_key: string;
            full: components["schemas"]["SignalWindowMetricItem"];
            /** Normalization */
            normalization: string;
            /** Output Type */
            output_type: string;
            /** Product Eligible */
            product_eligible: boolean;
            quality: components["schemas"]["QualitySummary"];
            /** Rationale */
            rationale: string;
            /** Rationale Type */
            rationale_type: string;
            /** Research Tier */
            research_tier: string;
            /**
             * Signal Dataset Artifact Id
             * Format: uuid
             */
            signal_dataset_artifact_id: string;
            /** Signal Key */
            signal_key: string;
            /** Stability */
            stability: components["schemas"]["SignalWindowMetricItem"][];
            /** Template Key */
            template_key: string;
        };
        /** SignalOverviewResponse */
        SignalOverviewResponse: {
            /** Common Period Count */
            common_period_count: number;
            context: components["schemas"]["ApiContext"];
            /**
             * Coverage End
             * Format: date
             */
            coverage_end: string;
            /**
             * Coverage Start
             * Format: date
             */
            coverage_start: string;
            /**
             * Data Bundle Artifact Id
             * Format: uuid
             */
            data_bundle_artifact_id: string;
            /**
             * Eligibility Artifact Id
             * Format: uuid
             */
            eligibility_artifact_id: string;
            /**
             * Evaluation Artifact Id
             * Format: uuid
             */
            evaluation_artifact_id: string;
            /**
             * Evaluation Engine Artifact Id
             * Format: uuid
             */
            evaluation_engine_artifact_id: string;
            /**
             * Forward Return Artifact Id
             * Format: uuid
             */
            forward_return_artifact_id: string;
            /**
             * Frequency
             * @enum {string}
             */
            frequency: "weekly" | "monthly";
            /** High Correlation Threshold */
            high_correlation_threshold: number;
            /** Issues */
            issues: components["schemas"]["SignalDiagnosticIssueItem"][];
            /** Pair Count */
            pair_count: number;
            /** Pairs */
            pairs: components["schemas"]["SignalPairDiagnosticItem"][];
            quality: components["schemas"]["QualitySummary"];
            /**
             * Signal Catalog Artifact Id
             * Format: uuid
             */
            signal_catalog_artifact_id: string;
            /** Signal Count */
            signal_count: number;
            /**
             * Signal Engine Artifact Id
             * Format: uuid
             */
            signal_engine_artifact_id: string;
            /** Signals */
            signals: components["schemas"]["SignalDiagnosticItem"][];
            /** Target Key */
            target_key: string;
            /**
             * Universe Artifact Id
             * Format: uuid
             */
            universe_artifact_id: string;
        };
        /** SignalPairDiagnosticItem */
        SignalPairDiagnosticItem: {
            /** High Correlation */
            high_correlation: boolean;
            /** Left Signal Key */
            left_signal_key: string;
            /** Mean Top2 Overlap */
            mean_top2_overlap: number;
            /** Right Signal Key */
            right_signal_key: string;
            /** Score Observation Count */
            score_observation_count: number;
            /** Score Spearman */
            score_spearman: number | null;
            /** Spread Correlation */
            spread_correlation: number | null;
            /** Spread Period Count */
            spread_period_count: number;
        };
        /** SignalWindowMetricItem */
        SignalWindowMetricItem: {
            /** Event Asset Concentration */
            event_asset_concentration: number | null;
            /** Event Rate */
            event_rate: number | null;
            /** Information Ratio */
            information_ratio: number | null;
            /** Mean Rank Ic */
            mean_rank_ic: number | null;
            /** Mean Top2 Turnover */
            mean_top2_turnover: number | null;
            /** Mean Top Bottom Spread */
            mean_top_bottom_spread: number;
            /** Median Rank Ic */
            median_rank_ic: number | null;
            /** Non Neutral Rate */
            non_neutral_rate: number;
            /** Period Count */
            period_count: number;
            /** Positive Ic Ratio */
            positive_ic_ratio: number | null;
            /** Undefined Ic Count */
            undefined_ic_count: number;
            /** Valid Ic Count */
            valid_ic_count: number;
            /**
             * Window End
             * Format: date
             */
            window_end: string;
            /** Window Key */
            window_key: string;
            /**
             * Window Start
             * Format: date
             */
            window_start: string;
        };
        /** SourceSnapshotItem */
        SourceSnapshotItem: {
            /**
             * Artifact Id
             * Format: uuid
             */
            artifact_id: string;
            /**
             * As Of At
             * Format: date-time
             */
            as_of_at: string;
            /**
             * Fetched At
             * Format: date-time
             */
            fetched_at: string;
            /** Payload Hash */
            payload_hash: string;
            /** Provider Key */
            provider_key: string;
            /** Raw Size Bytes */
            raw_size_bytes: number;
            /** Series Key */
            series_key: string;
            /** Snapshot Key */
            snapshot_key: string;
        };
        /** StrategyDecisionItem */
        StrategyDecisionItem: {
            /** Actual Holding Count */
            actual_holding_count: number;
            /** Boundary Tie Count */
            boundary_tie_count: number;
            /**
             * Decision Date
             * Format: date
             */
            decision_date: string;
            /** Positions */
            positions: components["schemas"]["StrategyTargetPositionItem"][];
            /** Reserve Target Weight */
            reserve_target_weight: number;
            /** Target K */
            target_k: number;
        };
        /** StrategyExecutionPolicyItem */
        StrategyExecutionPolicyItem: {
            /**
             * Artifact Id
             * Format: uuid
             */
            artifact_id: string;
            /** Delay Common Sessions */
            delay_common_sessions: number;
            /** Execution Price */
            execution_price: string;
            /** Missing Execution Policy */
            missing_execution_policy: string;
            /** Policy Key */
            policy_key: string;
        };
        /** StrategyOverviewResponse */
        StrategyOverviewResponse: {
            context: components["schemas"]["ApiContext"];
            /** Products */
            products: components["schemas"]["StrategyProductItem"][];
            quality: components["schemas"]["QualitySummary"];
            rules: components["schemas"]["StrategyRuleSetItem"];
            /** Target Paths */
            target_paths: components["schemas"]["StrategyTargetPathItem"][];
        };
        /** StrategyProductItem */
        StrategyProductItem: {
            /**
             * Artifact Id
             * Format: uuid
             */
            artifact_id: string;
            /** Execution Policy Key */
            execution_policy_key: string;
            /** Execution Price */
            execution_price: string;
            /**
             * Frequency
             * @enum {string}
             */
            frequency: "weekly" | "monthly";
            /** Model Output Type */
            model_output_type: string;
            /** Model Specification Key */
            model_specification_key: string;
            /** Model Specification Type */
            model_specification_type: string;
            /** Product Key */
            product_key: string;
            /** Research Tier */
            research_tier: string;
            /** Schedule Key */
            schedule_key: string;
            /** Target K */
            target_k: number;
            /** Target Path Count */
            target_path_count: number;
            /** Universe Key */
            universe_key: string;
            /** Variant Key */
            variant_key: string;
            /** Version Number */
            version_number: number;
        };
        /** StrategyRuleSetItem */
        StrategyRuleSetItem: {
            /** Allocation Contract */
            allocation_contract: string;
            /** Candidate Input Policy */
            candidate_input_policy: string;
            /** Compatible Model Output Types */
            compatible_model_output_types: string[];
            /**
             * Definition Artifact Id
             * Format: uuid
             */
            definition_artifact_id: string;
            execution_policy: components["schemas"]["StrategyExecutionPolicyItem"];
            /** Hypothesis */
            hypothesis: string;
            /** Missing Input Policy */
            missing_input_policy: string;
            /** Reserve Contract */
            reserve_contract: string;
            /** Schedules */
            schedules: components["schemas"]["StrategyScheduleItem"][];
            /** Selection Contract */
            selection_contract: string;
            /** Strategy Family */
            strategy_family: string;
            /** Strategy Key */
            strategy_key: string;
            /** Variants */
            variants: components["schemas"]["StrategyVariantItem"][];
            /**
             * Version Artifact Id
             * Format: uuid
             */
            version_artifact_id: string;
            /** Version Number */
            version_number: number;
        };
        /** StrategyScheduleItem */
        StrategyScheduleItem: {
            /**
             * Artifact Id
             * Format: uuid
             */
            artifact_id: string;
            /** Decision Data Policy */
            decision_data_policy: string;
            /** Decision Timing */
            decision_timing: string;
            /**
             * Frequency
             * @enum {string}
             */
            frequency: "weekly" | "monthly";
            /** Schedule Key */
            schedule_key: string;
        };
        /** StrategyTargetPathItem */
        StrategyTargetPathItem: {
            /**
             * Artifact Id
             * Format: uuid
             */
            artifact_id: string;
            /**
             * Coverage End
             * Format: date
             */
            coverage_end: string;
            /**
             * Coverage Start
             * Format: date
             */
            coverage_start: string;
            /** Decision Count */
            decision_count: number;
            /**
             * Frequency
             * @enum {string}
             */
            frequency: "weekly" | "monthly";
            /**
             * Model Dataset Artifact Id
             * Format: uuid
             */
            model_dataset_artifact_id: string;
            /** Model Specification Key */
            model_specification_key: string;
            /** Position Count */
            position_count: number;
            /**
             * Product Artifact Id
             * Format: uuid
             */
            product_artifact_id: string;
            /** Product Key */
            product_key: string;
            /** Target K */
            target_k: number;
            /** Variant Key */
            variant_key: string;
        };
        /** StrategyTargetPathResponse */
        StrategyTargetPathResponse: {
            /** Auxiliary Signal Dataset Artifact Id */
            auxiliary_signal_dataset_artifact_id: string | null;
            context: components["schemas"]["ApiContext"];
            /**
             * Data Bundle Artifact Id
             * Format: uuid
             */
            data_bundle_artifact_id: string;
            /** Decisions */
            decisions: components["schemas"]["StrategyDecisionItem"][];
            /**
             * Eligibility Artifact Id
             * Format: uuid
             */
            eligibility_artifact_id: string;
            /**
             * Engine Artifact Id
             * Format: uuid
             */
            engine_artifact_id: string;
            quality: components["schemas"]["QualitySummary"];
            target_path: components["schemas"]["StrategyTargetPathItem"];
            /**
             * Universe Artifact Id
             * Format: uuid
             */
            universe_artifact_id: string;
        };
        /** StrategyTargetPositionItem */
        StrategyTargetPositionItem: {
            /** Asset Key */
            asset_key: string;
            /** Decision Reason */
            decision_reason: string;
            /** Model Rank */
            model_rank: number;
            /** Model Score */
            model_score: number;
            /** Selected */
            selected: boolean;
            /** Selection Rank */
            selection_rank: number | null;
            /** Strategy Eligible */
            strategy_eligible: boolean;
            /** Symbol */
            symbol: string;
            /** Target Weight */
            target_weight: number;
            /** Trend State */
            trend_state: string | null;
        };
        /** StrategyVariantItem */
        StrategyVariantItem: {
            /**
             * Artifact Id
             * Format: uuid
             */
            artifact_id: string;
            /** Auxiliary Eligible State */
            auxiliary_eligible_state: string | null;
            /** Auxiliary Signal Key */
            auxiliary_signal_key: string | null;
            /** Empty Slot Policy */
            empty_slot_policy: string;
            /** Research Tier */
            research_tier: string;
            /** Reserve Rule */
            reserve_rule: string;
            /** Selection Order */
            selection_order: string;
            /** Slot Weight Rule */
            slot_weight_rule: string;
            /** Target K */
            target_k: number;
            /** Template Key */
            template_key: string;
            /** Tie Policy */
            tie_policy: string;
            /** Trend Filter */
            trend_filter: string;
            /** Variant Key */
            variant_key: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    artifacts_api_v2_artifacts_get: {
        parameters: {
            query?: {
                status?: string[] | null;
                artifact_type?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: {
                "if-none-match"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtifactListResponse"];
                };
            };
            /** @description Not modified */
            304: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    artifact_detail_api_v2_artifacts__artifact_id__get: {
        parameters: {
            query?: never;
            header?: {
                "if-none-match"?: string | null;
            };
            path: {
                artifact_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtifactDetailResponse"];
                };
            };
            /** @description Not modified */
            304: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    lineage_api_v2_artifacts__artifact_id__lineage_get: {
        parameters: {
            query?: never;
            header?: {
                "if-none-match"?: string | null;
            };
            path: {
                artifact_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LineageManifestResponse"];
                };
            };
            /** @description Not modified */
            304: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    capabilities_api_v2_capabilities_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CapabilitiesResponse"];
                };
            };
        };
    };
    asset_catalog_api_v2_catalog_assets_get: {
        parameters: {
            query?: never;
            header?: {
                "if-none-match"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetCatalogResponse"];
                };
            };
            /** @description Not modified */
            304: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    data_requirements_api_v2_catalog_data_requirements_get: {
        parameters: {
            query?: never;
            header?: {
                "if-none-match"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataRequirementResponse"];
                };
            };
            /** @description Not modified */
            304: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    product_compare_api_v2_compare_products_get: {
        parameters: {
            query: {
                result_artifact_id: string[];
            };
            header?: {
                "if-none-match"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductCompareResponse"];
                };
            };
            /** @description Not modified */
            304: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    data_overview_api_v2_data_overview_get: {
        parameters: {
            query?: never;
            header?: {
                "if-none-match"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataOverviewResponse"];
                };
            };
            /** @description Not modified */
            304: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    experiment_overview_api_v2_experiments_overview_get: {
        parameters: {
            query?: never;
            header?: {
                "if-none-match"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExperimentOverviewResponse"];
                };
            };
            /** @description Not modified */
            304: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    experiment_result_api_v2_experiments_results__artifact_id__get: {
        parameters: {
            query?: never;
            header?: {
                "if-none-match"?: string | null;
            };
            path: {
                artifact_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExperimentResultResponse"];
                };
            };
            /** @description Not modified */
            304: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    decision_explorer_api_v2_experiments_results__artifact_id__decisions_get: {
        parameters: {
            query?: {
                decision_date?: string | null;
            };
            header?: {
                "if-none-match"?: string | null;
            };
            path: {
                artifact_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DecisionExplorerResponse"];
                };
            };
            /** @description Not modified */
            304: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    factor_overview_api_v2_factors_overview_get: {
        parameters: {
            query?: never;
            header?: {
                "if-none-match"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FactorOverviewResponse"];
                };
            };
            /** @description Not modified */
            304: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_v2_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    model_overview_api_v2_models_overview_get: {
        parameters: {
            query?: {
                frequency?: "weekly" | "monthly";
            };
            header?: {
                "if-none-match"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelOverviewResponse"];
                };
            };
            /** @description Not modified */
            304: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    product_ranking_api_v2_rankings_products_get: {
        parameters: {
            query?: {
                cohort_artifact_id?: string | null;
                metric?: "net_sharpe" | "net_cagr" | "relative_wealth_growth" | "maximum_drawdown" | "calmar";
            };
            header?: {
                "if-none-match"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductRankingResponse"];
                };
            };
            /** @description Not modified */
            304: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    signal_overview_api_v2_signals_overview_get: {
        parameters: {
            query?: {
                frequency?: "weekly" | "monthly";
            };
            header?: {
                "if-none-match"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SignalOverviewResponse"];
                };
            };
            /** @description Not modified */
            304: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    strategy_overview_api_v2_strategies_overview_get: {
        parameters: {
            query?: never;
            header?: {
                "if-none-match"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrategyOverviewResponse"];
                };
            };
            /** @description Not modified */
            304: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    strategy_target_path_api_v2_strategies_targets__artifact_id__get: {
        parameters: {
            query?: never;
            header?: {
                "if-none-match"?: string | null;
            };
            path: {
                artifact_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrategyTargetPathResponse"];
                };
            };
            /** @description Not modified */
            304: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
