/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v2/artifacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Artifacts */
        get: operations["artifacts_api_v2_artifacts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/artifacts/{artifact_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Artifact Detail */
        get: operations["artifact_detail_api_v2_artifacts__artifact_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/artifacts/{artifact_id}/lineage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lineage */
        get: operations["lineage_api_v2_artifacts__artifact_id__lineage_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Capabilities */
        get: operations["capabilities_api_v2_capabilities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/catalog/assets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Asset Catalog */
        get: operations["asset_catalog_api_v2_catalog_assets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/catalog/data-requirements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Data Requirements */
        get: operations["data_requirements_api_v2_catalog_data_requirements_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v2_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ApiContext */
        ApiContext: {
            /**
             * Api Version
             * @default v2
             * @constant
             */
            api_version: "v2";
            /**
             * Read Only
             * @default true
             * @constant
             */
            read_only: true;
            /** System Version */
            system_version: string;
        };
        /** ArtifactDetailResponse */
        ArtifactDetailResponse: {
            artifact: components["schemas"]["ArtifactSummary"];
            context: components["schemas"]["ApiContext"];
            /** Direct Dependencies */
            direct_dependencies: components["schemas"]["DependencySummary"][];
            /** Direct Dependents */
            direct_dependents: components["schemas"]["DependencySummary"][];
            /** Lineage Url */
            lineage_url: string | null;
            quality: components["schemas"]["QualitySummary"];
        };
        /** ArtifactListResponse */
        ArtifactListResponse: {
            context: components["schemas"]["ApiContext"];
            /** Items */
            items: components["schemas"]["ArtifactSummary"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            quality: components["schemas"]["QualitySummary"];
            /** Total */
            total: number;
        };
        /** ArtifactSummary */
        ArtifactSummary: {
            /**
             * Artifact Id
             * Format: uuid
             */
            artifact_id: string;
            /** Artifact Key */
            artifact_key: string;
            /** Artifact Type */
            artifact_type: string;
            /** Content Hash */
            content_hash: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Published At */
            published_at: string | null;
            quality: components["schemas"]["QualitySummary"];
            /** Semantic Fingerprint */
            semantic_fingerprint: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "draft" | "published" | "retired" | "superseded" | "invalidated" | "tainted";
            /** Version Number */
            version_number: number;
        };
        /** AssetCatalogItem */
        AssetCatalogItem: {
            /**
             * Asset Id
             * Format: uuid
             */
            asset_id: string;
            /** Asset Key */
            asset_key: string;
            /** Asset Type */
            asset_type: string;
            /** Calendar Key */
            calendar_key: string;
            /** Classifications */
            classifications: {
                [key: string]: string;
            };
            /** Currency */
            currency: string;
            /** Name */
            name: string;
            /** Status */
            status: string;
            /** Symbol */
            symbol: string;
            /** Timezone */
            timezone: string;
            /** Universe Ordinal */
            universe_ordinal: number | null;
            /** Universe Role */
            universe_role: string | null;
            /** Venue Mic */
            venue_mic: string;
        };
        /** AssetCatalogResponse */
        AssetCatalogResponse: {
            /** As Of Date */
            as_of_date: string;
            context: components["schemas"]["ApiContext"];
            /** Items */
            items: components["schemas"]["AssetCatalogItem"][];
            quality: components["schemas"]["QualitySummary"];
            /**
             * Release Artifact Id
             * Format: uuid
             */
            release_artifact_id: string;
            /** Release Version Number */
            release_version_number: number;
            /** Universe Key */
            universe_key: string;
        };
        /** CapabilitiesResponse */
        CapabilitiesResponse: {
            context: components["schemas"]["ApiContext"];
            /** Domains */
            domains: components["schemas"]["DomainCapability"][];
            /** Endpoints */
            endpoints: string[];
            /** Interface States */
            interface_states: string[];
            /** Languages */
            languages: ("zh-CN" | "en")[];
            quality: components["schemas"]["QualitySummary"];
        };
        /** DataRequirementItem */
        DataRequirementItem: {
            /** Calendar Type */
            calendar_type: string;
            /** Fields */
            fields: string[];
            /** Interval Count */
            interval_count: number;
            /** Interval Unit */
            interval_unit: string;
            /** Requirement Key */
            requirement_key: string;
            /** Series Key */
            series_key: string;
            /** Session Type */
            session_type: string;
            /** Subject */
            subject: string;
            /** Timestamp Semantics */
            timestamp_semantics: string;
        };
        /** DataRequirementResponse */
        DataRequirementResponse: {
            /**
             * Artifact Id
             * Format: uuid
             */
            artifact_id: string;
            context: components["schemas"]["ApiContext"];
            /** Items */
            items: components["schemas"]["DataRequirementItem"][];
            quality: components["schemas"]["QualitySummary"];
            /** Requirement Set Key */
            requirement_set_key: string;
            /** Version Number */
            version_number: number;
        };
        /** DependencySummary */
        DependencySummary: {
            /**
             * Artifact Id
             * Format: uuid
             */
            artifact_id: string;
            /**
             * Depends On Artifact Id
             * Format: uuid
             */
            depends_on_artifact_id: string;
            /** Ordinal */
            ordinal: number | null;
            /** Role */
            role: string;
        };
        /** DomainCapability */
        DomainCapability: {
            /**
             * Availability
             * @enum {string}
             */
            availability: "available" | "planned";
            /** Delivery Milestone */
            delivery_milestone: string;
            /** Key */
            key: string;
            /** Purpose */
            purpose: string;
            /** Upstream */
            upstream: string[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            context: components["schemas"]["ApiContext"];
            /** Database Revision */
            database_revision: string | null;
            quality: components["schemas"]["QualitySummary"];
        };
        /** LineageManifestResponse */
        LineageManifestResponse: {
            /** Artifacts */
            artifacts: {
                [key: string]: unknown;
            }[];
            /** Canonical Version */
            canonical_version: string;
            context: components["schemas"]["ApiContext"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Dependencies */
            dependencies: components["schemas"]["DependencySummary"][];
            /** Manifest Hash */
            manifest_hash: string;
            quality: components["schemas"]["QualitySummary"];
            root_artifact: components["schemas"]["ArtifactSummary"];
        };
        /** QualitySummary */
        QualitySummary: {
            /** Codes */
            codes?: string[];
            /**
             * State
             * @enum {string}
             */
            state: "ok" | "partial" | "warning" | "error";
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    artifacts_api_v2_artifacts_get: {
        parameters: {
            query?: {
                status?: string[] | null;
                artifact_type?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: {
                "if-none-match"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtifactListResponse"];
                };
            };
            /** @description Not modified */
            304: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    artifact_detail_api_v2_artifacts__artifact_id__get: {
        parameters: {
            query?: never;
            header?: {
                "if-none-match"?: string | null;
            };
            path: {
                artifact_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtifactDetailResponse"];
                };
            };
            /** @description Not modified */
            304: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    lineage_api_v2_artifacts__artifact_id__lineage_get: {
        parameters: {
            query?: never;
            header?: {
                "if-none-match"?: string | null;
            };
            path: {
                artifact_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LineageManifestResponse"];
                };
            };
            /** @description Not modified */
            304: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    capabilities_api_v2_capabilities_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CapabilitiesResponse"];
                };
            };
        };
    };
    asset_catalog_api_v2_catalog_assets_get: {
        parameters: {
            query?: never;
            header?: {
                "if-none-match"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetCatalogResponse"];
                };
            };
            /** @description Not modified */
            304: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    data_requirements_api_v2_catalog_data_requirements_get: {
        parameters: {
            query?: never;
            header?: {
                "if-none-match"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataRequirementResponse"];
                };
            };
            /** @description Not modified */
            304: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_v2_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
}
