/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v2/artifacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Artifacts */
        get: operations["artifacts_api_v2_artifacts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/artifacts/{artifact_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Artifact Detail */
        get: operations["artifact_detail_api_v2_artifacts__artifact_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/artifacts/{artifact_id}/lineage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lineage */
        get: operations["lineage_api_v2_artifacts__artifact_id__lineage_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Capabilities */
        get: operations["capabilities_api_v2_capabilities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/catalog/assets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Asset Catalog */
        get: operations["asset_catalog_api_v2_catalog_assets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/catalog/data-requirements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Data Requirements */
        get: operations["data_requirements_api_v2_catalog_data_requirements_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/data/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Data Overview */
        get: operations["data_overview_api_v2_data_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/factors/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Factor Overview */
        get: operations["factor_overview_api_v2_factors_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v2_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ApiContext */
        ApiContext: {
            /**
             * Api Version
             * @default v2
             * @constant
             */
            api_version: "v2";
            /**
             * Read Only
             * @default true
             * @constant
             */
            read_only: true;
            /** System Version */
            system_version: string;
        };
        /** ArtifactDetailResponse */
        ArtifactDetailResponse: {
            artifact: components["schemas"]["ArtifactSummary"];
            context: components["schemas"]["ApiContext"];
            /** Direct Dependencies */
            direct_dependencies: components["schemas"]["DependencySummary"][];
            /** Direct Dependents */
            direct_dependents: components["schemas"]["DependencySummary"][];
            /** Lineage Url */
            lineage_url: string | null;
            quality: components["schemas"]["QualitySummary"];
        };
        /** ArtifactListResponse */
        ArtifactListResponse: {
            context: components["schemas"]["ApiContext"];
            /** Items */
            items: components["schemas"]["ArtifactSummary"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            quality: components["schemas"]["QualitySummary"];
            /** Total */
            total: number;
        };
        /** ArtifactSummary */
        ArtifactSummary: {
            /**
             * Artifact Id
             * Format: uuid
             */
            artifact_id: string;
            /** Artifact Key */
            artifact_key: string;
            /** Artifact Type */
            artifact_type: string;
            /** Content Hash */
            content_hash: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Published At */
            published_at: string | null;
            quality: components["schemas"]["QualitySummary"];
            /** Semantic Fingerprint */
            semantic_fingerprint: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "draft" | "published" | "retired" | "superseded" | "invalidated" | "tainted";
            /** Version Number */
            version_number: number;
        };
        /** AssetCatalogItem */
        AssetCatalogItem: {
            /**
             * Asset Id
             * Format: uuid
             */
            asset_id: string;
            /** Asset Key */
            asset_key: string;
            /** Asset Type */
            asset_type: string;
            /** Calendar Key */
            calendar_key: string;
            /** Classifications */
            classifications: {
                [key: string]: string;
            };
            /** Currency */
            currency: string;
            /** Name */
            name: string;
            /** Status */
            status: string;
            /** Symbol */
            symbol: string;
            /** Timezone */
            timezone: string;
            /** Universe Ordinal */
            universe_ordinal: number | null;
            /** Universe Role */
            universe_role: string | null;
            /** Venue Mic */
            venue_mic: string;
        };
        /** AssetCatalogResponse */
        AssetCatalogResponse: {
            /** As Of Date */
            as_of_date: string;
            context: components["schemas"]["ApiContext"];
            /** Items */
            items: components["schemas"]["AssetCatalogItem"][];
            quality: components["schemas"]["QualitySummary"];
            /**
             * Release Artifact Id
             * Format: uuid
             */
            release_artifact_id: string;
            /** Release Version Number */
            release_version_number: number;
            /** Universe Key */
            universe_key: string;
        };
        /** CapabilitiesResponse */
        CapabilitiesResponse: {
            context: components["schemas"]["ApiContext"];
            /** Domains */
            domains: components["schemas"]["DomainCapability"][];
            /** Endpoints */
            endpoints: string[];
            /** Interface States */
            interface_states: string[];
            /** Languages */
            languages: ("zh-CN" | "en")[];
            quality: components["schemas"]["QualitySummary"];
        };
        /** DataBundleItem */
        DataBundleItem: {
            /**
             * Artifact Id
             * Format: uuid
             */
            artifact_id: string;
            /** Bundle Key */
            bundle_key: string;
            /**
             * Coverage End
             * Format: date
             */
            coverage_end: string;
            /**
             * Coverage Start
             * Format: date
             */
            coverage_start: string;
            /** Member Count */
            member_count: number;
            /** Members */
            members: components["schemas"]["DataBundleMemberItem"][];
            /** Name */
            name: string;
            /** Version Number */
            version_number: number;
        };
        /** DataBundleMemberItem */
        DataBundleMemberItem: {
            /**
             * Artifact Id
             * Format: uuid
             */
            artifact_id: string;
            /** Artifact Key */
            artifact_key: string;
            /** Artifact Type */
            artifact_type: string;
            /** Ordinal */
            ordinal: number;
            /** Role */
            role: string;
            /** Version Number */
            version_number: number;
        };
        /** DataOverviewResponse */
        DataOverviewResponse: {
            bundle: components["schemas"]["DataBundleItem"] | null;
            context: components["schemas"]["ApiContext"];
            /** Datasets */
            datasets: components["schemas"]["DatasetPublicationItem"][];
            eligibility: components["schemas"]["EligibilitySnapshotItem"] | null;
            quality: components["schemas"]["QualitySummary"];
            /** Sources */
            sources: components["schemas"]["SourceSnapshotItem"][];
        };
        /** DataQualityIssueItem */
        DataQualityIssueItem: {
            /** Asset Key */
            asset_key: string | null;
            /** Details */
            details: {
                [key: string]: unknown;
            };
            /** Event Date */
            event_date: string | null;
            /** Message */
            message: string;
            /** Rule Code */
            rule_code: string;
            /**
             * Severity
             * @enum {string}
             */
            severity: "info" | "warning" | "error";
        };
        /** DataRequirementItem */
        DataRequirementItem: {
            /** Calendar Type */
            calendar_type: string;
            /** Fields */
            fields: string[];
            /** Interval Count */
            interval_count: number;
            /** Interval Unit */
            interval_unit: string;
            /** Requirement Key */
            requirement_key: string;
            /** Series Key */
            series_key: string;
            /** Session Type */
            session_type: string;
            /** Subject */
            subject: string;
            /** Timestamp Semantics */
            timestamp_semantics: string;
        };
        /** DataRequirementResponse */
        DataRequirementResponse: {
            /**
             * Artifact Id
             * Format: uuid
             */
            artifact_id: string;
            context: components["schemas"]["ApiContext"];
            /** Items */
            items: components["schemas"]["DataRequirementItem"][];
            quality: components["schemas"]["QualitySummary"];
            /** Requirement Set Key */
            requirement_set_key: string;
            /** Version Number */
            version_number: number;
        };
        /** DatasetCoverageItem */
        DatasetCoverageItem: {
            /** Asset Key */
            asset_key: string | null;
            /**
             * Coverage End
             * Format: date
             */
            coverage_end: string;
            /**
             * Coverage Start
             * Format: date
             */
            coverage_start: string;
            /** Missing Count */
            missing_count: number;
            /** Observation Count */
            observation_count: number;
            /** Subject Key */
            subject_key: string;
        };
        /** DatasetPublicationItem */
        DatasetPublicationItem: {
            /**
             * Artifact Id
             * Format: uuid
             */
            artifact_id: string;
            /** Coverage */
            coverage: components["schemas"]["DatasetCoverageItem"][];
            /**
             * Coverage End
             * Format: date
             */
            coverage_end: string;
            /**
             * Coverage Start
             * Format: date
             */
            coverage_start: string;
            /** Dataset Key */
            dataset_key: string;
            /**
             * Dataset Kind
             * @enum {string}
             */
            dataset_kind: "canonical" | "derived";
            /** Issues */
            issues: components["schemas"]["DataQualityIssueItem"][];
            quality: components["schemas"]["QualitySummary"];
            /** Row Count */
            row_count: number;
            /**
             * Value Kind
             * @enum {string}
             */
            value_kind: "daily_bar" | "rate_observation" | "reserve_return";
            /** Version Number */
            version_number: number;
        };
        /** DependencySummary */
        DependencySummary: {
            /**
             * Artifact Id
             * Format: uuid
             */
            artifact_id: string;
            /**
             * Depends On Artifact Id
             * Format: uuid
             */
            depends_on_artifact_id: string;
            /** Ordinal */
            ordinal: number | null;
            /** Role */
            role: string;
        };
        /** DomainCapability */
        DomainCapability: {
            /**
             * Availability
             * @enum {string}
             */
            availability: "available" | "planned";
            /** Delivery Milestone */
            delivery_milestone: string;
            /** Key */
            key: string;
            /** Purpose */
            purpose: string;
            /** Upstream */
            upstream: string[];
        };
        /** EligibilityAssetItem */
        EligibilityAssetItem: {
            /**
             * Asset Id
             * Format: uuid
             */
            asset_id: string;
            /** Asset Key */
            asset_key: string;
            /** Available End */
            available_end: string | null;
            /** Available Start */
            available_start: string | null;
            /** Data Ready Date */
            data_ready_date: string | null;
            /** Is Eligible */
            is_eligible: boolean;
            /** Issues */
            issues: components["schemas"]["EligibilityIssueItem"][];
            /** Observation Count */
            observation_count: number;
            /** Role */
            role: string;
            /** Symbol */
            symbol: string;
        };
        /** EligibilityIssueItem */
        EligibilityIssueItem: {
            /** Details */
            details: {
                [key: string]: unknown;
            };
            /** Issue Code */
            issue_code: string;
            /** Message */
            message: string;
            /**
             * Severity
             * @enum {string}
             */
            severity: "warning" | "error";
        };
        /** EligibilitySnapshotItem */
        EligibilitySnapshotItem: {
            /**
             * Artifact Id
             * Format: uuid
             */
            artifact_id: string;
            /** Eligible Count */
            eligible_count: number;
            /** Items */
            items: components["schemas"]["EligibilityAssetItem"][];
            /** Member Count */
            member_count: number;
            /**
             * Requested End
             * Format: date
             */
            requested_end: string;
            /**
             * Requested Start
             * Format: date
             */
            requested_start: string;
            /** Snapshot Key */
            snapshot_key: string;
            /** Warmup Observations */
            warmup_observations: number;
        };
        /** FactorCorrelationItem */
        FactorCorrelationItem: {
            /** High Correlation */
            high_correlation: boolean;
            /** Left Factor Key */
            left_factor_key: string;
            /** Left Variant Key */
            left_variant_key: string;
            /** Observation Count */
            observation_count: number;
            /** Right Factor Key */
            right_factor_key: string;
            /** Right Variant Key */
            right_variant_key: string;
            /** Same Definition */
            same_definition: boolean;
            /** Spearman Correlation */
            spearman_correlation: number | null;
        };
        /** FactorDatasetDiagnosticItem */
        FactorDatasetDiagnosticItem: {
            /** Asset Count */
            asset_count: number;
            /**
             * Coverage End
             * Format: date
             */
            coverage_end: string;
            /**
             * Coverage Start
             * Format: date
             */
            coverage_start: string;
            /**
             * Factor Dataset Artifact Id
             * Format: uuid
             */
            factor_dataset_artifact_id: string;
            /** Factor Key */
            factor_key: string;
            /** Formula */
            formula: string;
            /** Maximum */
            maximum: number;
            /** Mean */
            mean: number;
            /** Measurement Family */
            measurement_family: string;
            /** Median */
            median: number;
            /** Minimum */
            minimum: number;
            /** Missing Count */
            missing_count: number;
            /** Observation Count */
            observation_count: number;
            /** Output Unit */
            output_unit: string;
            /** P05 */
            p05: number;
            /** P25 */
            p25: number;
            /** P75 */
            p75: number;
            /** P95 */
            p95: number;
            /** Parameters */
            parameters: {
                [key: string]: unknown;
            };
            /** Preset Type */
            preset_type: string;
            quality: components["schemas"]["QualitySummary"];
            /** Row Count */
            row_count: number;
            /** Standard Deviation */
            standard_deviation: number;
            /** Variant Key */
            variant_key: string;
            /** Zero Variance */
            zero_variance: boolean;
        };
        /** FactorDiagnosticIssueItem */
        FactorDiagnosticIssueItem: {
            /** Details */
            details: {
                [key: string]: unknown;
            };
            /** Issue Code */
            issue_code: string;
            /** Message */
            message: string;
            /**
             * Severity
             * @enum {string}
             */
            severity: "info" | "warning" | "error";
            /** Variant Key */
            variant_key: string;
        };
        /** FactorOverviewResponse */
        FactorOverviewResponse: {
            /** Asset Count */
            asset_count: number;
            context: components["schemas"]["ApiContext"];
            /** Correlations */
            correlations: components["schemas"]["FactorCorrelationItem"][];
            /**
             * Coverage End
             * Format: date
             */
            coverage_end: string;
            /**
             * Coverage Start
             * Format: date
             */
            coverage_start: string;
            /**
             * Data Bundle Artifact Id
             * Format: uuid
             */
            data_bundle_artifact_id: string;
            /** Dataset Count */
            dataset_count: number;
            /** Datasets */
            datasets: components["schemas"]["FactorDatasetDiagnosticItem"][];
            /**
             * Diagnostic Artifact Id
             * Format: uuid
             */
            diagnostic_artifact_id: string;
            /**
             * Diagnostic Engine Artifact Id
             * Format: uuid
             */
            diagnostic_engine_artifact_id: string;
            /**
             * Eligibility Artifact Id
             * Format: uuid
             */
            eligibility_artifact_id: string;
            /**
             * Factor Catalog Artifact Id
             * Format: uuid
             */
            factor_catalog_artifact_id: string;
            /**
             * Factor Engine Artifact Id
             * Format: uuid
             */
            factor_engine_artifact_id: string;
            /** High Correlation Threshold */
            high_correlation_threshold: number;
            /** Issues */
            issues: components["schemas"]["FactorDiagnosticIssueItem"][];
            /** Observation Count */
            observation_count: number;
            /** Pair Count */
            pair_count: number;
            quality: components["schemas"]["QualitySummary"];
            /**
             * Universe Artifact Id
             * Format: uuid
             */
            universe_artifact_id: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            context: components["schemas"]["ApiContext"];
            /** Database Revision */
            database_revision: string | null;
            quality: components["schemas"]["QualitySummary"];
        };
        /** LineageManifestResponse */
        LineageManifestResponse: {
            /** Artifacts */
            artifacts: {
                [key: string]: unknown;
            }[];
            /** Canonical Version */
            canonical_version: string;
            context: components["schemas"]["ApiContext"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Dependencies */
            dependencies: components["schemas"]["DependencySummary"][];
            /** Manifest Hash */
            manifest_hash: string;
            quality: components["schemas"]["QualitySummary"];
            root_artifact: components["schemas"]["ArtifactSummary"];
        };
        /** QualitySummary */
        QualitySummary: {
            /** Codes */
            codes?: string[];
            /**
             * State
             * @enum {string}
             */
            state: "ok" | "partial" | "warning" | "error";
        };
        /** SourceSnapshotItem */
        SourceSnapshotItem: {
            /**
             * Artifact Id
             * Format: uuid
             */
            artifact_id: string;
            /**
             * As Of At
             * Format: date-time
             */
            as_of_at: string;
            /**
             * Fetched At
             * Format: date-time
             */
            fetched_at: string;
            /** Payload Hash */
            payload_hash: string;
            /** Provider Key */
            provider_key: string;
            /** Raw Size Bytes */
            raw_size_bytes: number;
            /** Series Key */
            series_key: string;
            /** Snapshot Key */
            snapshot_key: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    artifacts_api_v2_artifacts_get: {
        parameters: {
            query?: {
                status?: string[] | null;
                artifact_type?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: {
                "if-none-match"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtifactListResponse"];
                };
            };
            /** @description Not modified */
            304: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    artifact_detail_api_v2_artifacts__artifact_id__get: {
        parameters: {
            query?: never;
            header?: {
                "if-none-match"?: string | null;
            };
            path: {
                artifact_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtifactDetailResponse"];
                };
            };
            /** @description Not modified */
            304: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    lineage_api_v2_artifacts__artifact_id__lineage_get: {
        parameters: {
            query?: never;
            header?: {
                "if-none-match"?: string | null;
            };
            path: {
                artifact_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LineageManifestResponse"];
                };
            };
            /** @description Not modified */
            304: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    capabilities_api_v2_capabilities_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CapabilitiesResponse"];
                };
            };
        };
    };
    asset_catalog_api_v2_catalog_assets_get: {
        parameters: {
            query?: never;
            header?: {
                "if-none-match"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetCatalogResponse"];
                };
            };
            /** @description Not modified */
            304: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    data_requirements_api_v2_catalog_data_requirements_get: {
        parameters: {
            query?: never;
            header?: {
                "if-none-match"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataRequirementResponse"];
                };
            };
            /** @description Not modified */
            304: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    data_overview_api_v2_data_overview_get: {
        parameters: {
            query?: never;
            header?: {
                "if-none-match"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataOverviewResponse"];
                };
            };
            /** @description Not modified */
            304: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    factor_overview_api_v2_factors_overview_get: {
        parameters: {
            query?: never;
            header?: {
                "if-none-match"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FactorOverviewResponse"];
                };
            };
            /** @description Not modified */
            304: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_v2_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
}
