import i18n from "i18next";
import { initReactI18next } from "react-i18next";

export const supportedLanguages = ["zh-CN", "en"] as const;
export type SupportedLanguage = (typeof supportedLanguages)[number];

const zh = {
  brand: { name: "候鸟实验室", stage: "雏鸟阶段 · v0.2" },
  nav: { overview: "概览", dashboard: "研究台", research: "研究", assets: "资产", data: "数据", factors: "因子", signals: "信号", models: "模型", products: "产品", strategies: "策略", experiments: "实验", compare: "比较", system: "系统", artifacts: "发布物", runs: "运行记录", api: "API" },
  common: { loading: "正在读取已发布结果…", retry: "重新加载", noData: "暂无符合条件的已发布数据", readOnly: "只读研究环境", planned: "计划中", available: "已可用", version: "版本", status: "状态", quality: "质量", dependencies: "直接依赖", dependents: "直接下游", back: "返回发布物", open: "查看" },
  dashboard: { eyebrow: "RESEARCH PLATFORM", title: "从可追溯研究走向严格策略比较", subtitle: "完整策略结果现在只能在已发布的统一市场环境中排名；每个名次都保留区间、成本、基准、数据和引擎上下文。", systemHealth: "系统地基", publishedObjects: "已发布对象", currentScope: "当前能力边界", nextMilestone: "下一阶段", nextValue: "发布质量与正式品牌", traceHint: "每个正式结果都可以回到准确的定义、内容哈希和上游版本。" },
  artifact: { title: "不可变发布物", subtitle: "这里显示研究对象的身份与质量，不把策略表现混入前置层级。", allStatuses: "正式与异常状态", key: "对象键", type: "类型", fingerprint: "语义指纹", contentHash: "内容哈希", lineage: "血缘清单", manifest: "Manifest 哈希", canonical: "序列化规则" },
  assets: { title: "资产与研究范围", subtitle: "资产目录定义可交易对象的稳定身份、上市信息与分类；研究宇宙再明确候选资产和产品基准。这里不展示策略收益。", universe: "研究宇宙", asOf: "目录截至", candidates: "候选资产", benchmark: "产品基准", members: "当前宇宙成员", style: "风格分类", listing: "上市地", calendar: "交易日历", requirements: "后续数据必须满足的契约", rateNote: "DGS3MO 是现金收益模拟所需的参考利率序列，不是可交易资产，也不属于研究宇宙。" },
  data: { title: "数据质量与可用范围", subtitle: "沿着源快照、规范数据集、冻结数据包与资产可用性检查已发布的数据链。这里报告数据事实，不展示策略绩效。", sourceSnapshots: "源快照", datasets: "规范与衍生数据集", issues: "质量问题", eligible: "可用资产", publishedOnly: "仅显示已发布版本", coverage: "覆盖区间", rows: "记录数", bundle: "冻结数据包", eligibility: "资产可用性", warmup: "统一暖机观测数", ready: "可用", blocked: "受阻" },
  factor: { title: "因子诊断与参数实例", subtitle: "查看因子测量本身的覆盖、分布、参数稳定性与数值相关性。这里不赋予经济方向，也不展示策略收益。", context: "共同诊断区间", variants: "参数实例", assets: "资产", highPairs: "高相关组合", library: "因子实例与分布", lineage: "查看诊断血缘", mean: "均值", median: "中位数", std: "标准差", rows: "观测数", parameterStability: "参数稳定性", stabilityNote: "同一个因子定义下，不同参数窗口在相同资产与日期上的 Spearman 相关性。高相关表示测量结果相似，不代表策略有效。", redundancy: "冗余提醒", redundancyNote: "跨因子及同因子实例的 |ρ| 高相关只触发研究提醒，不会自动删除任何因子。", noPairs: "当前目录没有可比较的同定义参数组合。", noHighPairs: "当前共同区间没有触发阈值的高相关组合。", issues: "诊断问题" },
  signal: { title: "信号评价与经济方向", subtitle: "在明确的周频或月频未来收益目标上，查看方向性预测、区间稳定性、事件行为和冗余。这里是信号研究诊断，不是策略收益排名。", frequency: "评价频率", weekly: "周频", monthly: "月频", target: "未来收益目标", context: "共同评价区间", periods: "共同期数", signals: "信号数量", highPairs: "高相关组合", library: "信号目录与评价", lineage: "查看评价血缘", direction: "方向", output: "输出", rankIc: "平均 Rank IC", positiveIc: "正 IC 比例", topBottom: "Top-Bottom", informationRatio: "IC IR", activity: "事件 / 非中性率", turnover: "潜在 Top-2 换手", stability: "年度稳定性", noStability: "当前区间没有单独年度窗口。", redundancy: "信号冗余提醒", redundancyNote: "分数高相关、收益差相关和 Top-2 重合只帮助理解重复信息；系统不会自动删除信号。", scoreCorrelation: "分数 ρ", spreadCorrelation: "收益差相关", overlap: "Top-2 重合", noHighPairs: "当前共同样本没有触发阈值的高相关信号组合。", issues: "评价提示", sampleNote: "所有信号使用同一组四只候选 ETF 与共同目标日期；SPY 不参与横截面排序。" },
  model: { title: "模型结构与独立诊断", subtitle: "查看模型怎样组合维度和信号，以及它在共同预测目标上的稳定性、输出行为、冗余和受控消融。这里不展示策略收益排名。", frequency: "评价频率", weekly: "周频", monthly: "月频", target: "未来收益目标", context: "共同评价区间", periods: "共同期数", models: "模型数量", ablations: "全区间消融", sampleNote: "全部模型使用相同的四只候选 ETF、目标日期和共同有效样本；诊断结果不是扣费后的策略收益。", library: "模型目录与构成", lineage: "查看评价血缘", search: "搜索模型、方法或维度", showing: "显示 {{count}} / {{total}} 个筛选结果", loadMore: "再显示 20 个模型", openAblations: "展开 {{count}} 条全区间消融", type: { all: "全部", single_signal: "单信号", dimension_subset_equal_weight: "维度等权", fixed_weight: "固定权重", directional_vote: "方向投票" }, rankIc: "平均 Rank IC", positiveIc: "正 IC 比例", topBottom: "Top-Bottom", informationRatio: "IC IR", dispersion: "分数离散度", turnover: "潜在 Top-2 换手", composition: "维度与信号构成", stability: "年度稳定性", noStability: "当前区间没有单独年度窗口。", ablationTitle: "受控维度消融", ablationNote: "只比较等权维度子集与移除一个维度后的正式等权子模型；正差值表示完整模型在当前诊断指标上更高。", redundancy: "模型冗余提醒", redundancyNote: "高相关只描述模型输出重复，不会自动淘汰模型。这里只显示触发阈值的前 30 组。", scoreCorrelation: "分数 ρ", spreadCorrelation: "收益差相关", overlap: "Top-2 重合", noHighPairs: "当前共同样本没有触发阈值的高相关模型组合。" },
  strategy: { title: "策略规则与目标仓位", subtitle: "检查策略如何解释模型输出、形成完整产品身份，并把每个调仓日的候选资产转化为可追溯目标权重。这里不展示收益、Sharpe 或排行榜。", rules: "规则", products: "产品", targetPaths: "目标路径", variants: "策略变体", hypothesis: "研究假设", compatibleOutputs: "兼容模型输出", selectionOrder: "选择顺序", emptySlots: "空缺仓位", tiePolicy: "边界并列", execution: "执行", universe: "资产池", targetCount: "目标路径", noProducts: "尚未发布完整策略产品。", noPaths: "尚未发布目标仓位路径。", coverage: "覆盖区间", selectPath: "选择目标路径", selectDate: "选择调仓日", reserve: "储备权重", holdings: "实际持仓", boundaryTies: "边界并列", asset: "资产", score: "模型分数", rank: "模型排名", trend: "趋势状态", eligible: "策略可选", weight: "目标权重", reason: "决策原因", yes: "是", no: "否", lineage: "查看发布血缘", rulesNote: "K=2 是正式基准；K=1 与 K=3 是敏感性变体。高分、过滤、并列和储备规则均由已发布契约决定。", targetNote: "每条路径绑定模型数据集、策略产品、资产池、数据包、可用性快照与引擎版本；页面只读取已发布决策。" },
  experiment: { title: "策略实验与可追溯绩效", subtitle: "在明确且可比较的市场假设下，检查策略扣费后表现、产品基准和完整运行审计。排行只是当前模拟环境中的指标视图，不代表未来收益能力。", suites: "实验套件", cells: "实验单元", accepted: "已接受", failed: "失败", pending: "待运行", running: "运行中", all: "全部", strategy: "策略与模型", assumptions: "区间与市场假设", netCagr: "净 CAGR", benchmarkCagr: "基准 CAGR", sharpe: "净 Sharpe", drawdown: "最大回撤", comparisonNote: "只有前置假设一致的实验单元才适合直接比较；每个策略变体作为独立产品单元显示。", detail: "实验结果详情", lineage: "查看结果血缘", resolved: "实际有效区间", observations: "观测数", run: "运行尝试", metrics: "完整绩效指标", checks: "质量检查", events: "运行事件" },
  ranking: { title: "策略产品排行榜", cohort: "比较队列", metric: "排序指标", context: "共同指标区间", market: "市场环境", warmup: "统一暖机 / 数据就绪", candidates: "可排名 / 候选", rank: "名次", product: "模型与产品", configuration: "策略配置", selectedMetric: "当前排序值", netSharpe: "净 Sharpe", netCagr: "净 CAGR", relativeGrowth: "相对 SPY 年化复合收益", drawdown: "最大回撤", calmar: "Calmar", disclaimer: "名次只描述当前已发布历史模拟环境中的单一指标，不是综合评分，也不代表未来收益能力。Undefined 结果不参与名次。", openResult: "查看正式结果" },
  compare: { title: "策略产品比较", subtitle: "并排检查已接受结果；只有其他上下文完全相同且仅一个研究维度变化时，系统才标记为受控比较。", select: "选择结果", needTwo: "至少需要两个不同的已接受结果。", metric: "展示指标", controlled: "受控比较", side_by_side: "普通并排查看", identical: "相同结果语义", controlledNote: "只改变了 {{dimension}}；可以把差异作为这一维度的历史诊断线索。", sideNote: "多个维度或受保护上下文同时变化，不能把绩效差异归因给某一个因素。", identicalNote: "这些结果没有可识别的研究维度差异。", blockers: "不一致的受保护上下文", open: "查看实验", disclaimer: "受控比较仍是历史模拟诊断，不构成因果证明或未来收益承诺。" },
  decision: { title: "单次决策解释器", date: "决策日期", note: "沿已发布血缘展示这一调仓日实际使用的模型、信号、因子值和数据版本，不在浏览器中重算。", method: "模型聚合", holdings: "实际持仓", reserve: "储备权重", data: "数据包", score: "模型分数", rank: "模型名次", weight: "目标权重", components: "组件解释链", factorValue: "因子值", signalScore: "信号分数", contribution: "模型贡献", notExact: "投票模型不作线性归因" },
  api: { title: "只读 API", subtitle: "OpenAPI 是前后端共享契约。计算、发布、失效和重建仍只通过 CLI 执行。", docs: "打开交互式 API 文档", contract: "下载 OpenAPI JSON", ruleTitle: "边界规则", ruleBody: "API 只暴露 GET 查询，不在浏览器中提供任何写入或研究计算入口。" },
  planned: { title: "页面结构已经预留", body: "该领域将在 {{milestone}} 交付真实数据库、服务、API 与页面。现在不展示模拟研究结果。" },
  states: { ok: "正常", partial: "不完整", warning: "需注意", error: "不可用", published: "已发布", draft: "草稿", retired: "已退役", superseded: "已替代", tainted: "受污染", invalidated: "已失效" },
};

const en: typeof zh = {
  brand: { name: "Migration Lab", stage: "Fledgling stage · v0.2" },
  nav: { overview: "Overview", dashboard: "Research desk", research: "Research", assets: "Assets", data: "Data", factors: "Factors", signals: "Signals", models: "Models", products: "Products", strategies: "Strategies", experiments: "Experiments", compare: "Compare", system: "System", artifacts: "Artifacts", runs: "Runs", api: "API" },
  common: { loading: "Reading published results…", retry: "Reload", noData: "No matching published data", readOnly: "Read-only research environment", planned: "Planned", available: "Available", version: "Version", status: "Status", quality: "Quality", dependencies: "Direct dependencies", dependents: "Direct dependents", back: "Back to artifacts", open: "Open" },
  dashboard: { eyebrow: "RESEARCH PLATFORM", title: "Move from traceable research to strict product comparison", subtitle: "Complete Strategy results rank only inside a published common market context. Every rank retains its interval, cost, benchmark, data, and engine assumptions.", systemHealth: "System foundation", publishedObjects: "Published objects", currentScope: "Current capability boundary", nextMilestone: "Next milestone", nextValue: "Release quality and formal brand", traceHint: "Every formal result can return to its exact definition, content hash, and upstream versions." },
  artifact: { title: "Immutable artifacts", subtitle: "Research identity and quality live here; strategy performance is not projected onto upstream layers.", allStatuses: "Formal and exceptional states", key: "Object key", type: "Type", fingerprint: "Semantic fingerprint", contentHash: "Content hash", lineage: "Lineage manifest", manifest: "Manifest hash", canonical: "Serialization rule" },
  assets: { title: "Assets and research scope", subtitle: "The catalog defines stable tradable identities, listings, and classifications. The universe assigns candidate and product-benchmark roles without mixing in strategy performance.", universe: "Research universe", asOf: "Catalog as of", candidates: "Candidates", benchmark: "Product benchmark", members: "Current universe members", style: "Style exposure", listing: "Listing", calendar: "Trading calendar", requirements: "Required downstream data contract", rateNote: "DGS3MO is a reference-rate series used to simulate cash returns. It is not a tradable asset and is not a universe member." },
  data: { title: "Data quality and availability", subtitle: "Inspect the published chain from source snapshots through canonical datasets, the frozen bundle, and asset eligibility. This page reports data facts, not strategy performance.", sourceSnapshots: "Source snapshots", datasets: "Canonical and derived datasets", issues: "Quality issues", eligible: "Eligible assets", publishedOnly: "Published versions only", coverage: "Coverage", rows: "Rows", bundle: "Frozen data bundle", eligibility: "Asset eligibility", warmup: "Unified warm-up observations", ready: "Ready", blocked: "Blocked" },
  factor: { title: "Factor diagnostics and variants", subtitle: "Inspect coverage, distributions, parameter stability, and value correlation for factor measurements. No economic direction or strategy return is assigned here.", context: "Common diagnostic range", variants: "Parameter variants", assets: "Assets", highPairs: "High-correlation pairs", library: "Factor variants and distributions", lineage: "Open diagnostic lineage", mean: "Mean", median: "Median", std: "Std. dev.", rows: "Observations", parameterStability: "Parameter stability", stabilityNote: "Spearman correlation across identical asset-date observations for parameter variants of the same factor definition. Similar measurements do not imply strategy effectiveness.", redundancy: "Redundancy alerts", redundancyNote: "High |ρ| across factor values triggers a research alert only. No factor is removed automatically.", noPairs: "The catalog has no same-definition parameter pairs to compare.", noHighPairs: "No pair crosses the alert threshold in this context.", issues: "Diagnostic issues" },
  signal: { title: "Signal evaluation and economic direction", subtitle: "Inspect directional prediction, interval stability, event behavior, and redundancy against an explicit weekly or monthly forward-return target. These are Signal diagnostics, not strategy performance rankings.", frequency: "Evaluation frequency", weekly: "Weekly", monthly: "Monthly", target: "Forward-return target", context: "Common evaluation range", periods: "Common periods", signals: "Signals", highPairs: "High-correlation pairs", library: "Signal catalog and evaluation", lineage: "Open evaluation lineage", direction: "Direction", output: "Output", rankIc: "Mean Rank IC", positiveIc: "Positive IC ratio", topBottom: "Top-Bottom", informationRatio: "IC IR", activity: "Event / non-neutral rate", turnover: "Potential Top-2 turnover", stability: "Calendar-year stability", noStability: "No separate calendar-year window is available.", redundancy: "Signal redundancy alerts", redundancyNote: "Score correlation, spread correlation, and Top-2 overlap describe repeated information. No Signal is removed automatically.", scoreCorrelation: "Score ρ", spreadCorrelation: "Spread corr.", overlap: "Top-2 overlap", noHighPairs: "No Signal pair crosses the alert threshold in this common sample.", issues: "Evaluation notices", sampleNote: "Every Signal uses the same four candidate ETFs and common target dates. SPY is excluded from the cross-sectional ranking." },
  model: { title: "Model structure and independent diagnostics", subtitle: "Inspect how each Model combines dimensions and Signals, together with stability, output behavior, redundancy, and controlled ablation against a common target. Strategy performance rankings do not appear here.", frequency: "Evaluation frequency", weekly: "Weekly", monthly: "Monthly", target: "Forward-return target", context: "Common evaluation range", periods: "Common periods", models: "Models", ablations: "Full-window ablations", sampleNote: "Every Model uses the same four candidate ETFs, target dates, and common valid sample. Diagnostics are not net strategy returns.", library: "Model catalog and composition", lineage: "Open evaluation lineage", search: "Search Model, method, or dimension", showing: "Showing {{count}} of {{total}} filtered Models", loadMore: "Show 20 more Models", openAblations: "Open {{count}} full-window ablations", type: { all: "All", single_signal: "Single Signal", dimension_subset_equal_weight: "Equal-weight dimensions", fixed_weight: "Fixed weight", directional_vote: "Directional vote" }, rankIc: "Mean Rank IC", positiveIc: "Positive IC ratio", topBottom: "Top-Bottom", informationRatio: "IC IR", dispersion: "Score dispersion", turnover: "Potential Top-2 turnover", composition: "Dimension and Signal composition", stability: "Calendar-year stability", noStability: "No separate calendar-year window is available.", ablationTitle: "Controlled dimension ablation", ablationNote: "Only equal-weight dimension subsets are compared with their formally published child after removing one dimension. A positive delta means the full Model is higher on that diagnostic metric.", redundancy: "Model redundancy alerts", redundancyNote: "High correlation describes repeated Model output and never removes a Model automatically. Only the first 30 threshold alerts are shown.", scoreCorrelation: "Score ρ", spreadCorrelation: "Spread corr.", overlap: "Top-2 overlap", noHighPairs: "No Model pair crosses the alert threshold in this common sample." },
  strategy: { title: "Strategy rules and target weights", subtitle: "Inspect how a Strategy interprets Model output, forms a complete product identity, and converts every rebalance date into traceable target weights. Returns, Sharpe, and rankings do not appear here.", rules: "Rules", products: "Products", targetPaths: "Target paths", variants: "Strategy variants", hypothesis: "Research hypothesis", compatibleOutputs: "Compatible Model outputs", selectionOrder: "Selection order", emptySlots: "Empty slots", tiePolicy: "Boundary ties", execution: "Execution", universe: "Universe", targetCount: "Target paths", noProducts: "No complete Strategy Product has been published.", noPaths: "No target-weight path has been published.", coverage: "Coverage", selectPath: "Select target path", selectDate: "Select decision date", reserve: "Reserve weight", holdings: "Actual holdings", boundaryTies: "Boundary ties", asset: "Asset", score: "Model score", rank: "Model rank", trend: "Trend state", eligible: "Eligible", weight: "Target weight", reason: "Decision reason", yes: "Yes", no: "No", lineage: "Open artifact lineage", rulesNote: "K=2 is canonical; K=1 and K=3 are sensitivity variants. Ranking, filtering, ties, and reserve behavior are frozen in published contracts.", targetNote: "Every path binds a Model Dataset, Strategy Product, universe, data bundle, eligibility snapshot, and engine version. The page only reads published decisions." },
  experiment: { title: "Strategy experiments and traceable performance", subtitle: "Inspect net strategy performance, the product benchmark, and the complete run audit under explicit, comparable market assumptions. A ranking is only a metric view in the simulated environment, not a claim about future returns.", suites: "Suites", cells: "Experiment cells", accepted: "Accepted", failed: "Failed", pending: "Pending", running: "Running", all: "All", strategy: "Strategy and Model", assumptions: "Interval and assumptions", netCagr: "Net CAGR", benchmarkCagr: "Benchmark CAGR", sharpe: "Net Sharpe", drawdown: "Maximum drawdown", comparisonNote: "Only cells with identical upstream assumptions are directly comparable. Every Strategy variant remains a separate product cell.", detail: "Experiment result detail", lineage: "Open result lineage", resolved: "Resolved interval", observations: "Observations", run: "Run attempt", metrics: "Complete performance metrics", checks: "Quality checks", events: "Run events" },
  ranking: { title: "Strategy Product Ranking", cohort: "Comparison cohort", metric: "Ranking metric", context: "Common metric interval", market: "Market context", warmup: "Unified warm-up / data ready", candidates: "Ranked / candidates", rank: "Rank", product: "Model and product", configuration: "Strategy configuration", selectedMetric: "Selected value", netSharpe: "Net Sharpe", netCagr: "Net CAGR", relativeGrowth: "Annualized relative wealth vs SPY", drawdown: "Maximum drawdown", calmar: "Calmar", disclaimer: "A rank describes one metric inside the current published historical simulation context. It is not a composite score or a claim about future returns. Undefined results do not rank.", openResult: "Open accepted result" },
  compare: { title: "Strategy Product Compare", subtitle: "Inspect accepted results side by side. The system labels a comparison controlled only when every protected context matches and exactly one research dimension changes.", select: "Select results", needTwo: "At least two distinct accepted results are required.", metric: "Displayed metric", controlled: "Controlled comparison", side_by_side: "Side-by-side view", identical: "Identical result semantics", controlledNote: "Only {{dimension}} changed; the difference is a historical diagnostic clue for that dimension.", sideNote: "Multiple dimensions or protected contexts changed, so performance differences cannot be attributed to one factor.", identicalNote: "These results have no identifiable research-dimension difference.", blockers: "Mismatched protected context", open: "Open experiment", disclaimer: "A controlled historical comparison is not causal proof or a promise of future returns." },
  decision: { title: "Decision Explorer", date: "Decision date", note: "Follow the published lineage for the Model, Signal, Factor values, and Data version actually used on this rebalance date. The browser does not recompute them.", method: "Model aggregation", holdings: "Actual holdings", reserve: "Reserve weight", data: "Data bundle", score: "Model score", rank: "Model rank", weight: "Target weight", components: "Component trace", factorValue: "Factor value", signalScore: "Signal score", contribution: "Model contribution", notExact: "No linear attribution for vote models" },
  api: { title: "Read-only API", subtitle: "OpenAPI is the shared frontend/backend contract. Calculation, publication, invalidation, and rebuild remain CLI-only.", docs: "Open interactive API docs", contract: "Download OpenAPI JSON", ruleTitle: "Boundary rule", ruleBody: "The API exposes GET queries only. The browser has no write or research-computation entry point." },
  planned: { title: "The page boundary is reserved", body: "This domain receives its real database, service, API, and page in {{milestone}}. No simulated research results are shown now." },
  states: { ok: "Healthy", partial: "Partial", warning: "Attention", error: "Unavailable", published: "Published", draft: "Draft", retired: "Retired", superseded: "Superseded", tainted: "Tainted", invalidated: "Invalidated" },
};

function initialLanguage(): SupportedLanguage {
  const urlLanguage = new URLSearchParams(window.location.search).get("lang");
  if (urlLanguage === "en" || urlLanguage === "zh-CN") return urlLanguage;
  return window.localStorage.getItem("style-rotation-language") === "en" ? "en" : "zh-CN";
}

void i18n.use(initReactI18next).init({
  resources: { "zh-CN": { translation: zh }, en: { translation: en } },
  lng: initialLanguage(), fallbackLng: "en", interpolation: { escapeValue: false },
});

export async function setLanguage(language: SupportedLanguage): Promise<void> {
  window.localStorage.setItem("style-rotation-language", language);
  const url = new URL(window.location.href);
  url.searchParams.set("lang", language);
  window.history.replaceState({}, "", `${url.pathname}${url.search}${url.hash}`);
  document.documentElement.lang = language;
  await i18n.changeLanguage(language);
}

export default i18n;
